"""
Curated College Dataset
=======================
100 Indian engineering colleges with comprehensive details.
Each college has: fees, courses, admission process, placements, facilities, etc.
"""

COLLEGES = [
    # ============================================================
    # TRICHY REGION COLLEGES (1-15)
    # ============================================================
    {
        "id": 1,
        "name": "University College of Engineering, BIT Campus, Tiruchirappalli",
        "short_name": "BIT Campus Trichy",
        "established": 1986,
        "type": "Government",
        "affiliation": "Anna University",
        "accreditation": "NAAC A+, NBA Accredited",
        "nirf_ranking": "101-150 (Engineering)",
        "city": "Tiruchirappalli",
        "district": "Tiruchirappalli",
        "state": "Tamil Nadu",
        "pincode": "620024",
        "address": "BIT Campus, Srirangam, Tiruchirappalli - 620024",
        "courses_ug": "B.E. Computer Science and Engineering; B.E. Electronics and Communication Engineering; B.E. Electrical and Electronics Engineering; B.E. Mechanical Engineering; B.E. Civil Engineering; B.Tech Information Technology",
        "courses_pg": "M.E. Computer Science and Engineering; M.E. VLSI Design; M.E. Structural Engineering; M.E. Power Systems Engineering; MBA; MCA",
        "courses_phd": "Computer Science; Electronics; Mechanical Engineering; Civil Engineering",
        "fees_ug": "₹15,000 - ₹50,000 per year (Government quota)",
        "fees_pg": "₹20,000 - ₹60,000 per year",
        "fees_hostel": "₹10,000 - ₹15,000 per year",
        "fees_total_estimate": "₹1.5 - ₹3 Lakhs (4-year B.E.)",
        "admission_ug": "Through TNEA counselling based on HSC (+2) marks or JEE Main score. Apply online at tneaonline.org during May-June.",
        "admission_pg": "Through TANCA counselling based on GATE or TANCET score. Apply during March-April.",
        "admission_docs": "10th Marksheet; 12th Marksheet; Community Certificate; Transfer Certificate; Migration Certificate; Passport-size Photos; Aadhar Card",
        "admission_cutoff": "TNEA Cutoff: OC - 180+/200, BC - 170+/200 (varies by branch and year)",
        "placement_avg": "₹4.5 LPA",
        "placement_highest": "₹18 LPA",
        "placement_median": "₹3.8 LPA",
        "placement_rate": "78%",
        "placement_recruiters": "TCS; Infosys; Wipro; Cognizant; Zoho; HCL; Accenture; IBM; Capgemini; L&T Infotech",
        "facilities": "Central Library; Hostel (Boys & Girls); Sports Complex; Computer Lab; WiFi Campus; Canteen; Seminar Hall; Workshops; NSS; NCC",
        "website": "https://www.aubit.edu.in",
        "phone": "+91-431-2407988",
        "email": "principal@aubit.edu.in",
        "highlights": "Part of Anna University system; One of the oldest engineering colleges in Trichy; Strong alumni network in IT sector; Very affordable government fees; Beautiful campus in Srirangam; Active placement cell; Strong CSE and IT departments",
        "description": "University College of Engineering BIT Campus is a prestigious government engineering college in Tiruchirappalli, established in 1986 as a constituent college of Anna University. Known for its affordable education, strong academics, and good placement record, it is one of the most sought-after government engineering colleges in Tamil Nadu."
    },
    {
        "id": 2,
        "name": "National Institute of Technology, Tiruchirappalli",
        "short_name": "NIT Trichy",
        "established": 1964,
        "type": "Government (Institute of National Importance)",
        "affiliation": "Autonomous (MHRD)",
        "accreditation": "NAAC A++, NBA Accredited, NIRF Top 10",
        "nirf_ranking": "9 (Engineering 2024)",
        "city": "Tiruchirappalli",
        "district": "Tiruchirappalli",
        "state": "Tamil Nadu",
        "pincode": "620015",
        "address": "Tanjore Main Road, National Highway 67, Tiruchirappalli - 620015",
        "courses_ug": "B.Tech Computer Science; B.Tech ECE; B.Tech EEE; B.Tech Mechanical; B.Tech Civil; B.Tech Chemical; B.Tech Metallurgical; B.Tech Production; B.Tech Instrumentation; B.Arch Architecture",
        "courses_pg": "M.Tech in 25+ specializations; MBA; MCA; M.Sc Physics; M.Sc Chemistry; M.Sc Mathematics",
        "courses_phd": "All engineering and science departments",
        "fees_ug": "₹1.5 - ₹2 Lakhs per year",
        "fees_pg": "₹1 - ₹1.5 Lakhs per year",
        "fees_hostel": "₹25,000 - ₹40,000 per year",
        "fees_total_estimate": "₹8 - ₹10 Lakhs (4-year B.Tech)",
        "admission_ug": "Through JEE Main followed by JoSAA counselling. Top 2.5 lakh JEE Main qualifiers eligible.",
        "admission_pg": "Through GATE score followed by CCMT counselling. Some programs accept TANCET.",
        "admission_docs": "JEE Main Scorecard; 10th & 12th Marksheets; Category Certificate; Photo ID; Passport Photos",
        "admission_cutoff": "JEE Main Cutoff: General - 15,000-25,000 rank (CSE), varies by branch",
        "placement_avg": "₹12 LPA",
        "placement_highest": "₹1.2 Crore (International)",
        "placement_median": "₹9 LPA",
        "placement_rate": "92%",
        "placement_recruiters": "Google; Microsoft; Amazon; Goldman Sachs; Qualcomm; Texas Instruments; Samsung; Oracle; Adobe; Deloitte; McKinsey",
        "facilities": "Central Library (24/7); Hostels; Olympic Swimming Pool; Indoor Stadium; Gymnasium; Research Labs; Incubation Centre; Hospital; ATM; Shopping Complex; Auditorium",
        "website": "https://www.nitt.edu",
        "phone": "+91-431-2503000",
        "email": "registrar@nitt.edu",
        "highlights": "NIRF Rank 9 among engineering colleges; Institute of National Importance; Pragyan (National Level Tech Fest); Festember (Cultural Fest); 800+ acre campus; World-class research facilities; Strong international collaborations; Excellent ROI",
        "description": "NIT Tiruchirappalli is one of India's premier engineering institutions, consistently ranked among the top 10 engineering colleges in the country. Established in 1964, it offers world-class education, outstanding placements, and a vibrant campus life on its sprawling 800-acre campus."
    },
    {
        "id": 3,
        "name": "Saranathan College of Engineering",
        "short_name": "SCE Trichy",
        "established": 2001,
        "type": "Private (Self-Financing)",
        "affiliation": "Anna University",
        "accreditation": "NAAC A, NBA Accredited",
        "nirf_ranking": "201-300 (Engineering)",
        "city": "Tiruchirappalli",
        "district": "Tiruchirappalli",
        "state": "Tamil Nadu",
        "pincode": "620012",
        "address": "Venkateswara Nagar, Panjappur, Tiruchirappalli - 620012",
        "courses_ug": "B.E. Computer Science; B.E. ECE; B.E. EEE; B.E. Mechanical; B.E. Civil; B.Tech IT; B.E. Automobile; B.Tech Artificial Intelligence",
        "courses_pg": "M.E. Computer Science; M.E. Communication Systems; M.E. Power Electronics; MBA",
        "courses_phd": "Computer Science; ECE; Mechanical",
        "fees_ug": "₹75,000 - ₹1,25,000 per year",
        "fees_pg": "₹50,000 - ₹80,000 per year",
        "fees_hostel": "₹50,000 - ₹75,000 per year",
        "fees_total_estimate": "₹4 - ₹6 Lakhs (4-year B.E.)",
        "admission_ug": "Through TNEA counselling based on HSC marks. Management quota seats also available.",
        "admission_pg": "Through TANCA counselling based on GATE/TANCET scores.",
        "admission_docs": "10th Marksheet; 12th Marksheet; Community Certificate; TC; Photos; Aadhar",
        "admission_cutoff": "TNEA Cutoff: OC - 170+/200 (CSE), varies by branch",
        "placement_avg": "₹3.8 LPA",
        "placement_highest": "₹12 LPA",
        "placement_median": "₹3.2 LPA",
        "placement_rate": "72%",
        "placement_recruiters": "TCS; Infosys; Wipro; CTS; HCL; Accenture; Mindtree; Mphasis; Tech Mahindra",
        "facilities": "Library; Hostel; Labs; Canteen; Sports Ground; WiFi; Auditorium; Transport; Gym",
        "website": "https://www.saranathan.ac.in",
        "phone": "+91-431-2467890",
        "email": "info@saranathan.ac.in",
        "highlights": "Strong placement record; Good infrastructure; Active student clubs; Industry partnerships; Affordable private college; Well-maintained campus",
        "description": "Saranathan College of Engineering is a well-known private engineering college in Tiruchirappalli, affiliated to Anna University. Known for its consistent placement record and quality education, it is one of the preferred choices for engineering aspirants in the Trichy region."
    },
    {
        "id": 4,
        "name": "J.J. College of Engineering and Technology",
        "short_name": "JJCET Trichy",
        "established": 1994,
        "type": "Private (Self-Financing)",
        "affiliation": "Anna University",
        "accreditation": "NAAC A, NBA Accredited",
        "nirf_ranking": "201-300 (Engineering)",
        "city": "Tiruchirappalli",
        "district": "Tiruchirappalli",
        "state": "Tamil Nadu",
        "pincode": "620009",
        "address": "Poolangulathupatti, Tiruchirappalli - 620009",
        "courses_ug": "B.E. Computer Science; B.E. ECE; B.E. EEE; B.E. Mechanical; B.E. Civil; B.Tech IT; B.E. Biomedical",
        "courses_pg": "M.E. Computer Science; M.E. Applied Electronics; M.E. CAD/CAM; MBA; MCA",
        "courses_phd": "CSE; ECE; Mechanical; Civil",
        "fees_ug": "₹70,000 - ₹1,10,000 per year",
        "fees_pg": "₹45,000 - ₹70,000 per year",
        "fees_hostel": "₹45,000 - ₹65,000 per year",
        "fees_total_estimate": "₹3.5 - ₹5.5 Lakhs (4-year B.E.)",
        "admission_ug": "Through TNEA counselling based on HSC marks. Management quota available.",
        "admission_pg": "Through TANCA counselling based on GATE/TANCET scores.",
        "admission_docs": "10th Marksheet; 12th Marksheet; Community Certificate; TC; Photos; Aadhar",
        "admission_cutoff": "TNEA Cutoff: OC - 168+/200 (CSE)",
        "placement_avg": "₹3.5 LPA",
        "placement_highest": "₹10 LPA",
        "placement_median": "₹3.0 LPA",
        "placement_rate": "70%",
        "placement_recruiters": "TCS; Infosys; Wipro; CTS; HCL; Accenture; Zoho; L&T",
        "facilities": "Library; Hostel; Labs; Sports; WiFi; Canteen; Auditorium; Transport",
        "website": "https://www.jjcet.ac.in",
        "phone": "+91-431-2660063",
        "email": "info@jjcet.ac.in",
        "highlights": "One of the oldest private colleges in Trichy; Strong ECE and CSE departments; Good campus infrastructure; Active alumni network",
        "description": "J.J. College of Engineering and Technology is a well-established private engineering college in Tiruchirappalli, known for its quality technical education and consistent placements since 1994."
    },
    {
        "id": 5,
        "name": "M.A.M. College of Engineering and Technology",
        "short_name": "MAMCE Trichy",
        "established": 1985,
        "type": "Private (Self-Financing)",
        "affiliation": "Anna University",
        "accreditation": "NAAC B++, NBA Accredited",
        "nirf_ranking": "Not Ranked",
        "city": "Tiruchirappalli",
        "district": "Tiruchirappalli",
        "state": "Tamil Nadu",
        "pincode": "621105",
        "address": "Siruganur, Tiruchirappalli - 621105",
        "courses_ug": "B.E. Computer Science; B.E. ECE; B.E. EEE; B.E. Mechanical; B.E. Civil",
        "courses_pg": "M.E. Computer Science; M.E. Power Systems; MBA",
        "courses_phd": "CSE; Mechanical",
        "fees_ug": "₹60,000 - ₹95,000 per year",
        "fees_pg": "₹40,000 - ₹65,000 per year",
        "fees_hostel": "₹40,000 - ₹60,000 per year",
        "fees_total_estimate": "₹3 - ₹4.5 Lakhs (4-year B.E.)",
        "admission_ug": "Through TNEA counselling or management quota.",
        "admission_pg": "Through TANCA counselling.",
        "admission_docs": "10th Marksheet; 12th Marksheet; Community Certificate; TC; Photos",
        "admission_cutoff": "TNEA Cutoff: OC - 160+/200 (CSE)",
        "placement_avg": "₹3.2 LPA",
        "placement_highest": "₹8 LPA",
        "placement_median": "₹2.8 LPA",
        "placement_rate": "65%",
        "placement_recruiters": "TCS; Infosys; Wipro; CTS; HCL; Accenture",
        "facilities": "Library; Hostel; Labs; Sports; WiFi; Canteen; Transport",
        "website": "https://www.mamce.org",
        "phone": "+91-431-2680200",
        "email": "info@mamce.org",
        "highlights": "One of the oldest private engineering colleges in Trichy; Affordable fees; Experienced faculty; Good campus",
        "description": "M.A.M. College of Engineering and Technology is one of the pioneering private engineering colleges in Tiruchirappalli, providing quality engineering education since 1985."
    },
    {
        "id": 6,
        "name": "M.I.E.T. Engineering College",
        "short_name": "MIET Trichy",
        "established": 2000,
        "type": "Private (Self-Financing)",
        "affiliation": "Anna University",
        "accreditation": "NAAC A, NBA Accredited",
        "nirf_ranking": "Not Ranked",
        "city": "Tiruchirappalli",
        "district": "Tiruchirappalli",
        "state": "Tamil Nadu",
        "pincode": "620007",
        "address": "Gundur, Tiruchirappalli - 620007",
        "courses_ug": "B.E. Computer Science; B.E. ECE; B.E. EEE; B.E. Mechanical; B.E. Civil; B.Tech IT; B.E. Aeronautical",
        "courses_pg": "M.E. Computer Science; M.E. VLSI; M.E. Thermal Engineering; MBA",
        "courses_phd": "CSE; ECE",
        "fees_ug": "₹70,000 - ₹1,15,000 per year",
        "fees_pg": "₹50,000 - ₹75,000 per year",
        "fees_hostel": "₹50,000 - ₹70,000 per year",
        "fees_total_estimate": "₹3.5 - ₹5 Lakhs (4-year B.E.)",
        "admission_ug": "Through TNEA counselling or management quota.",
        "admission_pg": "Through TANCA counselling.",
        "admission_docs": "10th Marksheet; 12th Marksheet; Community Certificate; TC; Photos",
        "admission_cutoff": "TNEA Cutoff: OC - 165+/200 (CSE)",
        "placement_avg": "₹3.5 LPA",
        "placement_highest": "₹10 LPA",
        "placement_median": "₹3.0 LPA",
        "placement_rate": "70%",
        "placement_recruiters": "TCS; Infosys; Wipro; CTS; HCL; Accenture; Mindtree",
        "facilities": "Library; Hostel; Labs; Sports; WiFi; Canteen; Auditorium; Transport; Gym",
        "website": "https://www.miet.edu",
        "phone": "+91-431-2660200",
        "email": "info@miet.edu",
        "highlights": "Well-maintained campus; Strong placement cell; Aeronautical engineering available; Industry collaborations",
        "description": "M.I.E.T. Engineering College is a reputed private college in Tiruchirappalli offering diverse engineering programs with good infrastructure and placement support."
    },
    {
        "id": 7,
        "name": "Cauvery College of Engineering and Technology",
        "short_name": "CCET Trichy",
        "established": 2001,
        "type": "Private (Self-Financing)",
        "affiliation": "Anna University",
        "accreditation": "NAAC B+",
        "nirf_ranking": "Not Ranked",
        "city": "Tiruchirappalli",
        "district": "Tiruchirappalli",
        "state": "Tamil Nadu",
        "pincode": "620018",
        "address": "Karur Main Road, Tiruchirappalli - 620018",
        "courses_ug": "B.E. Computer Science; B.E. ECE; B.E. EEE; B.E. Mechanical; B.E. Civil",
        "courses_pg": "M.E. Computer Science; MBA",
        "courses_phd": "Not Available",
        "fees_ug": "₹55,000 - ₹85,000 per year",
        "fees_pg": "₹40,000 - ₹60,000 per year",
        "fees_hostel": "₹35,000 - ₹55,000 per year",
        "fees_total_estimate": "₹2.8 - ₹4 Lakhs (4-year B.E.)",
        "admission_ug": "Through TNEA counselling or management quota.",
        "admission_pg": "Through TANCA counselling.",
        "admission_docs": "10th Marksheet; 12th Marksheet; Community Certificate; TC; Photos",
        "admission_cutoff": "TNEA Cutoff: OC - 155+/200 (CSE)",
        "placement_avg": "₹3.0 LPA",
        "placement_highest": "₹7 LPA",
        "placement_median": "₹2.5 LPA",
        "placement_rate": "60%",
        "placement_recruiters": "TCS; Infosys; Wipro; CTS; HCL",
        "facilities": "Library; Hostel; Labs; Sports; WiFi; Canteen; Transport",
        "website": "https://www.ccet.org.in",
        "phone": "+91-431-2611177",
        "email": "info@ccet.org.in",
        "highlights": "Affordable private college; Decent placement record; Growing infrastructure",
        "description": "Cauvery College of Engineering and Technology is an affordable private engineering college in Tiruchirappalli providing quality education in core engineering branches."
    },
    {
        "id": 8,
        "name": "Indra Ganesan College of Engineering",
        "short_name": "IGCE Trichy",
        "established": 2001,
        "type": "Private (Self-Financing)",
        "affiliation": "Anna University",
        "accreditation": "NAAC B+",
        "nirf_ranking": "Not Ranked",
        "city": "Tiruchirappalli",
        "district": "Tiruchirappalli",
        "state": "Tamil Nadu",
        "pincode": "620012",
        "address": "Manikandam, Tiruchirappalli - 620012",
        "courses_ug": "B.E. Computer Science; B.E. ECE; B.E. EEE; B.E. Mechanical; B.Tech IT",
        "courses_pg": "M.E. Computer Science; M.E. Applied Electronics",
        "courses_phd": "Not Available",
        "fees_ug": "₹55,000 - ₹85,000 per year",
        "fees_pg": "₹40,000 - ₹60,000 per year",
        "fees_hostel": "₹35,000 - ₹50,000 per year",
        "fees_total_estimate": "₹2.8 - ₹4 Lakhs (4-year B.E.)",
        "admission_ug": "Through TNEA counselling or management quota.",
        "admission_pg": "Through TANCA counselling.",
        "admission_docs": "10th Marksheet; 12th Marksheet; Community Certificate; TC; Photos",
        "admission_cutoff": "TNEA Cutoff: Moderate",
        "placement_avg": "₹2.8 LPA",
        "placement_highest": "₹6 LPA",
        "placement_median": "₹2.5 LPA",
        "placement_rate": "58%",
        "placement_recruiters": "TCS; Infosys; Wipro; CTS; HCL",
        "facilities": "Library; Hostel; Labs; Sports; WiFi; Canteen; Transport",
        "website": "https://www.igceng.org",
        "phone": "+91-431-2690124",
        "email": "info@igceng.org",
        "highlights": "Affordable fees; Good campus environment; Growing placement record",
        "description": "Indra Ganesan College of Engineering is a private engineering college in Tiruchirappalli offering quality technical education at affordable fees."
    },
    {
        "id": 9,
        "name": "Government College of Engineering, Srirangam",
        "short_name": "GCE Srirangam",
        "established": 2014,
        "type": "Government",
        "affiliation": "Anna University",
        "accreditation": "Applying for NAAC",
        "nirf_ranking": "Not Ranked",
        "city": "Tiruchirappalli",
        "district": "Tiruchirappalli",
        "state": "Tamil Nadu",
        "pincode": "620006",
        "address": "Srirangam, Tiruchirappalli - 620006",
        "courses_ug": "B.E. Computer Science; B.E. ECE; B.E. EEE; B.E. Mechanical; B.E. Civil",
        "courses_pg": "Not Available Yet",
        "courses_phd": "Not Available",
        "fees_ug": "₹5,000 - ₹15,000 per year (Government quota)",
        "fees_pg": "Not Available",
        "fees_hostel": "₹8,000 - ₹12,000 per year",
        "fees_total_estimate": "₹0.5 - ₹1 Lakh (4-year B.E.)",
        "admission_ug": "Through TNEA counselling based on HSC marks.",
        "admission_pg": "Not Available",
        "admission_docs": "10th Marksheet; 12th Marksheet; Community Certificate; TC; Photos",
        "admission_cutoff": "TNEA Cutoff: OC - 185+/200 (CSE)",
        "placement_avg": "₹3.0 LPA",
        "placement_highest": "₹6 LPA",
        "placement_median": "₹2.5 LPA",
        "placement_rate": "55%",
        "placement_recruiters": "TCS; Infosys; Wipro; CTS",
        "facilities": "Library; Labs; Sports Ground; WiFi; Canteen",
        "website": "https://www.gcesrirangam.ac.in",
        "phone": "+91-431-2432100",
        "email": "principal@gcesrirangam.ac.in",
        "highlights": "Extremely affordable government college; New but growing; Very low fees; Anna University curriculum",
        "description": "Government College of Engineering Srirangam is a new government engineering college in Tiruchirappalli offering extremely affordable engineering education under Anna University."
    },
    {
        "id": 10,
        "name": "Trichy Engineering College",
        "short_name": "TEC Trichy",
        "established": 2008,
        "type": "Private (Self-Financing)",
        "affiliation": "Anna University",
        "accreditation": "NAAC B",
        "nirf_ranking": "Not Ranked",
        "city": "Tiruchirappalli",
        "district": "Tiruchirappalli",
        "state": "Tamil Nadu",
        "pincode": "621132",
        "address": "Konalai, Musiri Taluk, Tiruchirappalli - 621132",
        "courses_ug": "B.E. Computer Science; B.E. ECE; B.E. EEE; B.E. Mechanical; B.E. Civil",
        "courses_pg": "M.E. Computer Science",
        "courses_phd": "Not Available",
        "fees_ug": "₹50,000 - ₹80,000 per year",
        "fees_pg": "₹40,000 - ₹60,000 per year",
        "fees_hostel": "₹35,000 - ₹50,000 per year",
        "fees_total_estimate": "₹2.5 - ₹3.5 Lakhs (4-year B.E.)",
        "admission_ug": "Through TNEA counselling or management quota.",
        "admission_pg": "Through TANCA counselling.",
        "admission_docs": "10th Marksheet; 12th Marksheet; Community Certificate; TC; Photos",
        "admission_cutoff": "TNEA Cutoff: Moderate",
        "placement_avg": "₹2.5 LPA",
        "placement_highest": "₹5 LPA",
        "placement_median": "₹2.2 LPA",
        "placement_rate": "50%",
        "placement_recruiters": "TCS; Infosys; Wipro; CTS",
        "facilities": "Library; Hostel; Labs; Sports; Canteen; Transport",
        "website": "https://www.tec.edu.in",
        "phone": "+91-431-2450123",
        "email": "info@tec.edu.in",
        "highlights": "Affordable private college; Growing campus; Rural setting",
        "description": "Trichy Engineering College is a private engineering college near Tiruchirappalli offering affordable engineering education."
    },
    {
        "id": 11,
        "name": "SRM Institute of Science and Technology, Tiruchirappalli",
        "short_name": "SRM TRP Trichy",
        "established": 2012,
        "type": "Private (Deemed University)",
        "affiliation": "SRM University (Autonomous)",
        "accreditation": "NAAC A++",
        "nirf_ranking": "36 (University)",
        "city": "Tiruchirappalli",
        "district": "Tiruchirappalli",
        "state": "Tamil Nadu",
        "pincode": "621105",
        "address": "Irungalur, Mannachanallur, Tiruchirappalli - 621105",
        "courses_ug": "B.Tech Computer Science; B.Tech AI & ML; B.Tech Data Science; B.Tech ECE; B.Tech EEE; B.Tech Mechanical; B.Tech Civil; B.Tech Biotechnology",
        "courses_pg": "M.Tech CSE; M.Tech VLSI; MBA; MCA",
        "courses_phd": "All engineering departments",
        "fees_ug": "₹1.5 - ₹2.5 Lakhs per year",
        "fees_pg": "₹1 - ₹1.5 Lakhs per year",
        "fees_hostel": "₹80,000 - ₹1.2 Lakhs per year",
        "fees_total_estimate": "₹8 - ₹12 Lakhs (4-year B.Tech)",
        "admission_ug": "Through SRMJEEE (SRM Joint Engineering Entrance Exam) conducted in April-May.",
        "admission_pg": "Through SRM entrance exam or GATE score.",
        "admission_docs": "SRMJEEE Scorecard; 10th & 12th Marksheets; TC; Photos; Aadhar",
        "admission_cutoff": "SRMJEEE rank-based counselling",
        "placement_avg": "₹5.5 LPA",
        "placement_highest": "₹20 LPA",
        "placement_median": "₹4.5 LPA",
        "placement_rate": "82%",
        "placement_recruiters": "Amazon; Google; Microsoft; TCS; Infosys; Wipro; Cognizant; Zoho; HCL; Accenture; IBM",
        "facilities": "Central Library; AC Hostels; Sports Complex; Swimming Pool; Gym; Labs; Incubation Centre; Auditorium; Cafeteria; Medical Centre",
        "website": "https://www.srmist.edu.in/trichy",
        "phone": "+91-431-2258000",
        "email": "admissions.trp@srmist.edu.in",
        "highlights": "Part of SRM University group; Modern campus with premium facilities; Strong placement record; International collaborations; NAAC A++ rated; AI/ML and Data Science programs",
        "description": "SRM Institute of Science and Technology Tiruchirappalli is a branch campus of the renowned SRM University, offering modern engineering programs with state-of-the-art facilities and strong corporate connections."
    },
    {
        "id": 12,
        "name": "K. Ramakrishnan College of Engineering",
        "short_name": "KRCE Trichy",
        "established": 2008,
        "type": "Private (Self-Financing)",
        "affiliation": "Anna University",
        "accreditation": "NAAC A",
        "nirf_ranking": "Not Ranked",
        "city": "Tiruchirappalli",
        "district": "Tiruchirappalli",
        "state": "Tamil Nadu",
        "pincode": "621112",
        "address": "Samayapuram, Tiruchirappalli - 621112",
        "courses_ug": "B.E. Computer Science; B.E. ECE; B.E. EEE; B.E. Mechanical; B.E. Civil; B.Tech IT; B.E. AI & DS",
        "courses_pg": "M.E. Computer Science; M.E. Communication Systems; MBA",
        "courses_phd": "CSE; ECE",
        "fees_ug": "₹65,000 - ₹1,00,000 per year",
        "fees_pg": "₹45,000 - ₹70,000 per year",
        "fees_hostel": "₹45,000 - ₹65,000 per year",
        "fees_total_estimate": "₹3.5 - ₹5 Lakhs (4-year B.E.)",
        "admission_ug": "Through TNEA counselling or management quota.",
        "admission_pg": "Through TANCA counselling.",
        "admission_docs": "10th Marksheet; 12th Marksheet; Community Certificate; TC; Photos",
        "admission_cutoff": "TNEA Cutoff: OC - 163+/200 (CSE)",
        "placement_avg": "₹3.5 LPA",
        "placement_highest": "₹10 LPA",
        "placement_median": "₹3.0 LPA",
        "placement_rate": "68%",
        "placement_recruiters": "TCS; Infosys; Wipro; CTS; HCL; Accenture; Zoho",
        "facilities": "Library; Hostel; Labs; Sports; WiFi; Canteen; Auditorium; Transport; Gym",
        "website": "https://www.krce.ac.in",
        "phone": "+91-431-2690500",
        "email": "info@krce.ac.in",
        "highlights": "NAAC A accredited; Growing placement record; AI & Data Science program; Well-equipped labs",
        "description": "K. Ramakrishnan College of Engineering is a NAAC A-accredited private college in Tiruchirappalli with modern programs including AI & Data Science."
    },
    {
        "id": 13,
        "name": "Periyar Maniammai Institute of Science and Technology",
        "short_name": "PMIST Thanjavur",
        "established": 1988,
        "type": "Private (Deemed University)",
        "affiliation": "Deemed University (UGC)",
        "accreditation": "NAAC A, NBA Accredited",
        "nirf_ranking": "101-150 (University)",
        "city": "Thanjavur",
        "district": "Thanjavur",
        "state": "Tamil Nadu",
        "pincode": "613403",
        "address": "Periyar Nagar, Vallam, Thanjavur - 613403",
        "courses_ug": "B.Tech CSE; B.Tech ECE; B.Tech EEE; B.Tech Mechanical; B.Tech Civil; B.Tech Biotech; B.Tech Chemical; B.Arch",
        "courses_pg": "M.Tech in 15+ specializations; MBA; MCA; M.Sc",
        "courses_phd": "All departments",
        "fees_ug": "₹1 - ₹1.8 Lakhs per year",
        "fees_pg": "₹75,000 - ₹1.2 Lakhs per year",
        "fees_hostel": "₹60,000 - ₹90,000 per year",
        "fees_total_estimate": "₹5 - ₹8 Lakhs (4-year B.Tech)",
        "admission_ug": "Through university entrance exam or merit-based admission.",
        "admission_pg": "Through GATE/university entrance exam.",
        "admission_docs": "10th & 12th Marksheets; Entrance Exam Score; TC; Photos; Aadhar",
        "admission_cutoff": "Merit-based",
        "placement_avg": "₹4.0 LPA",
        "placement_highest": "₹12 LPA",
        "placement_median": "₹3.5 LPA",
        "placement_rate": "72%",
        "placement_recruiters": "TCS; Infosys; Wipro; CTS; HCL; Accenture; L&T; Bosch",
        "facilities": "Central Library; Hostels; Research Labs; Sports Complex; Gym; WiFi Campus; Medical Centre; Auditorium",
        "website": "https://www.pmu.edu",
        "phone": "+91-4362-264600",
        "email": "admissions@pmu.edu",
        "highlights": "Deemed University status; Strong research output; Wide range of programs; Near Trichy; Good campus",
        "description": "Periyar Maniammai Institute is a deemed university near Tiruchirappalli offering diverse engineering and science programs with research focus."
    },
    {
        "id": 14,
        "name": "Dhanalakshmi Srinivasan College of Engineering and Technology",
        "short_name": "DSCET Trichy",
        "established": 2006,
        "type": "Private (Self-Financing)",
        "affiliation": "Anna University",
        "accreditation": "NAAC B+",
        "nirf_ranking": "Not Ranked",
        "city": "Perambalur",
        "district": "Perambalur",
        "state": "Tamil Nadu",
        "pincode": "621212",
        "address": "Mamallapuram, Perambalur - 621212 (Near Trichy)",
        "courses_ug": "B.E. Computer Science; B.E. ECE; B.E. EEE; B.E. Mechanical; B.E. Civil",
        "courses_pg": "M.E. Computer Science; MBA",
        "courses_phd": "Not Available",
        "fees_ug": "₹55,000 - ₹85,000 per year",
        "fees_pg": "₹40,000 - ₹60,000 per year",
        "fees_hostel": "₹35,000 - ₹55,000 per year",
        "fees_total_estimate": "₹2.8 - ₹4 Lakhs (4-year B.E.)",
        "admission_ug": "Through TNEA counselling or management quota.",
        "admission_pg": "Through TANCA counselling.",
        "admission_docs": "10th Marksheet; 12th Marksheet; Community Certificate; TC; Photos",
        "admission_cutoff": "TNEA Cutoff: Moderate",
        "placement_avg": "₹2.8 LPA",
        "placement_highest": "₹6 LPA",
        "placement_median": "₹2.5 LPA",
        "placement_rate": "55%",
        "placement_recruiters": "TCS; Infosys; Wipro; CTS",
        "facilities": "Library; Hostel; Labs; Sports; Canteen; Transport",
        "website": "https://www.dsgroup.org",
        "phone": "+91-4328-277177",
        "email": "info@dsgroup.org",
        "highlights": "Part of DS Group of institutions; Large campus; Affordable fees",
        "description": "Dhanalakshmi Srinivasan College of Engineering is part of the DS Group and offers affordable engineering education near Tiruchirappalli."
    },
    {
        "id": 15,
        "name": "Pavendar Bharathidasan College of Engineering and Technology",
        "short_name": "PBCET Trichy",
        "established": 2008,
        "type": "Private (Self-Financing)",
        "affiliation": "Anna University",
        "accreditation": "NAAC B",
        "nirf_ranking": "Not Ranked",
        "city": "Tiruchirappalli",
        "district": "Tiruchirappalli",
        "state": "Tamil Nadu",
        "pincode": "620024",
        "address": "Mathur, Tiruchirappalli - 620024",
        "courses_ug": "B.E. Computer Science; B.E. ECE; B.E. EEE; B.E. Mechanical",
        "courses_pg": "Not Available",
        "courses_phd": "Not Available",
        "fees_ug": "₹45,000 - ₹75,000 per year",
        "fees_pg": "Not Available",
        "fees_hostel": "₹30,000 - ₹45,000 per year",
        "fees_total_estimate": "₹2 - ₹3.5 Lakhs (4-year B.E.)",
        "admission_ug": "Through TNEA counselling or management quota.",
        "admission_pg": "Not Available",
        "admission_docs": "10th Marksheet; 12th Marksheet; Community Certificate; TC; Photos",
        "admission_cutoff": "TNEA Cutoff: Moderate-Low",
        "placement_avg": "₹2.5 LPA",
        "placement_highest": "₹4 LPA",
        "placement_median": "₹2.2 LPA",
        "placement_rate": "45%",
        "placement_recruiters": "TCS; Infosys; Wipro",
        "facilities": "Library; Hostel; Labs; Sports; Canteen",
        "website": "https://www.pbcet.edu.in",
        "phone": "+91-431-2450200",
        "email": "info@pbcet.edu.in",
        "highlights": "Very affordable; Small class sizes; Personal attention",
        "description": "Pavendar Bharathidasan College is a small, affordable private engineering college in Tiruchirappalli."
    },
    # ============================================================
    # TOP IITs (16-30)
    # ============================================================
    {
        "id": 16,
        "name": "Indian Institute of Technology Madras",
        "short_name": "IIT Madras",
        "established": 1959,
        "type": "Government (Institute of National Importance)",
        "affiliation": "Autonomous (MHRD)",
        "accreditation": "NAAC A++, NIRF #1",
        "nirf_ranking": "1 (Overall & Engineering 2024)",
        "city": "Chennai",
        "district": "Chennai",
        "state": "Tamil Nadu",
        "pincode": "600036",
        "address": "IIT P.O., Chennai - 600036",
        "courses_ug": "B.Tech CSE; B.Tech EE; B.Tech ME; B.Tech CE; B.Tech Chemical; B.Tech Metallurgy; B.Tech Aerospace; B.Tech Engineering Physics; B.Tech Naval Architecture; B.Des; Dual Degree in 10+ branches",
        "courses_pg": "M.Tech in 40+ specializations; MBA; M.Sc in 8 departments; MA in English/Development Studies",
        "courses_phd": "All departments (150+ research areas)",
        "fees_ug": "₹2 - ₹2.5 Lakhs per year",
        "fees_pg": "₹1.5 - ₹2 Lakhs per year (MBA: ₹10 Lakhs total)",
        "fees_hostel": "₹30,000 - ₹50,000 per year",
        "fees_total_estimate": "₹10 - ₹12 Lakhs (4-year B.Tech)",
        "admission_ug": "Through JEE Advanced (Top 15,000 JEE Main qualifiers take JEE Advanced). JoSAA counselling.",
        "admission_pg": "GATE score for M.Tech, CAT for MBA, JAM for M.Sc.",
        "admission_docs": "JEE Advanced Scorecard; 10th & 12th Marksheets; Category Certificate; Photo ID",
        "admission_cutoff": "JEE Advanced Cutoff: General - Top 500 (CSE), varies by branch",
        "placement_avg": "₹21 LPA",
        "placement_highest": "₹2.1 Crore (International)",
        "placement_median": "₹18 LPA",
        "placement_rate": "95%",
        "placement_recruiters": "Google; Microsoft; Apple; Amazon; Goldman Sachs; JP Morgan; McKinsey; BCG; Qualcomm; Samsung; Intel; NVIDIA; Uber; Flipkart",
        "facilities": "World-class Research Labs; 600-acre Deer Park campus; Central Library; 20+ Hostels; Swimming Pool; Stadium; Hospital; Banks; Post Office; Shopping Complex; IIT Madras Research Park",
        "website": "https://www.iitm.ac.in",
        "phone": "+91-44-22578000",
        "email": "registrar@iitm.ac.in",
        "highlights": "NIRF #1 in India (Overall); Located inside a National Park; IIT Madras Research Park; Strong startup ecosystem; BS in Data Science (online); Shaastra (Tech Fest); Top research output in India",
        "description": "IIT Madras is India's #1 ranked institution, set in a stunning 600-acre campus inside Guindy National Park. Known for its exceptional academics, groundbreaking research, and outstanding placements, it is the gold standard of engineering education in India."
    },
    {
        "id": 17,
        "name": "Indian Institute of Technology Bombay",
        "short_name": "IIT Bombay",
        "established": 1958,
        "type": "Government (Institute of National Importance)",
        "affiliation": "Autonomous (MHRD)",
        "accreditation": "NAAC A++, NIRF Top 3",
        "nirf_ranking": "3 (Engineering 2024)",
        "city": "Mumbai",
        "district": "Mumbai",
        "state": "Maharashtra",
        "pincode": "400076",
        "address": "Powai, Mumbai - 400076",
        "courses_ug": "B.Tech CSE; B.Tech EE; B.Tech ME; B.Tech Chemical; B.Tech CE; B.Tech Aerospace; B.Tech Metallurgy; B.Tech Engineering Physics; B.Des; Dual Degrees",
        "courses_pg": "M.Tech in 35+ specializations; MBA; M.Sc; M.Des; MA",
        "courses_phd": "All departments",
        "fees_ug": "₹2 - ₹2.5 Lakhs per year",
        "fees_pg": "₹1.5 - ₹2 Lakhs per year",
        "fees_hostel": "₹30,000 - ₹50,000 per year",
        "fees_total_estimate": "₹10 - ₹12 Lakhs (4-year B.Tech)",
        "admission_ug": "Through JEE Advanced followed by JoSAA counselling.",
        "admission_pg": "GATE for M.Tech, CAT for MBA, JAM for M.Sc.",
        "admission_docs": "JEE Advanced Scorecard; Marksheets; Category Certificate; Photo ID",
        "admission_cutoff": "JEE Advanced: General - Top 300 (CSE)",
        "placement_avg": "₹23 LPA",
        "placement_highest": "₹2.3 Crore (International)",
        "placement_median": "₹20 LPA",
        "placement_rate": "96%",
        "placement_recruiters": "Google; Microsoft; Apple; Goldman Sachs; Morgan Stanley; Tower Research; DE Shaw; Uber; Flipkart; Samsung; Qualcomm",
        "facilities": "Powai Lake campus; 550-acre campus; 16 Hostels; Olympic Pool; Gymkhana; Hospital; Research Labs; Incubation Centre",
        "website": "https://www.iitb.ac.in",
        "phone": "+91-22-25722545",
        "email": "registrar@iitb.ac.in",
        "highlights": "Iconic Powai campus; Techfest (Asia's largest tech fest); Strong finance placements; Entrepreneurship cell; World-class research",
        "description": "IIT Bombay is one of India's most prestigious engineering institutions, located on the banks of Powai Lake in Mumbai. Renowned for exceptional academics, record-breaking placements, and vibrant campus culture."
    },
    {
        "id": 18,
        "name": "Indian Institute of Technology Delhi",
        "short_name": "IIT Delhi",
        "established": 1961,
        "type": "Government (Institute of National Importance)",
        "affiliation": "Autonomous (MHRD)",
        "accreditation": "NAAC A++, NIRF Top 3",
        "nirf_ranking": "2 (Engineering 2024)",
        "city": "New Delhi",
        "district": "New Delhi",
        "state": "Delhi",
        "pincode": "110016",
        "address": "Hauz Khas, New Delhi - 110016",
        "courses_ug": "B.Tech CSE; B.Tech EE; B.Tech ME; B.Tech CE; B.Tech Chemical; B.Tech Textile; B.Tech Engineering Physics; B.Tech Biotech; Dual Degrees",
        "courses_pg": "M.Tech in 30+ specializations; MBA; M.Sc; M.Des",
        "courses_phd": "All departments",
        "fees_ug": "₹2 - ₹2.5 Lakhs per year",
        "fees_pg": "₹1.5 - ₹2 Lakhs per year",
        "fees_hostel": "₹25,000 - ₹45,000 per year",
        "fees_total_estimate": "₹10 - ₹12 Lakhs (4-year B.Tech)",
        "admission_ug": "Through JEE Advanced followed by JoSAA counselling.",
        "admission_pg": "GATE for M.Tech, CAT for MBA.",
        "admission_docs": "JEE Advanced Scorecard; Marksheets; Category Certificate",
        "admission_cutoff": "JEE Advanced: General - Top 400 (CSE)",
        "placement_avg": "₹22 LPA",
        "placement_highest": "₹2.0 Crore",
        "placement_median": "₹19 LPA",
        "placement_rate": "95%",
        "placement_recruiters": "Google; Microsoft; Amazon; Goldman Sachs; McKinsey; BCG; Bain; Samsung; Qualcomm; Adobe; Oracle",
        "facilities": "320-acre Hauz Khas campus; Central Library; 13 Hostels; Sports Complex; Hospital; Research Park",
        "website": "https://www.iitd.ac.in",
        "phone": "+91-11-26591999",
        "email": "registrar@iitd.ac.in",
        "highlights": "Located in heart of Delhi; NIRF #2; Strong consulting & finance placements; Rendezvous (cultural fest); Tryst (tech fest)",
        "description": "IIT Delhi is India's #2 ranked engineering institution, located in the prestigious Hauz Khas area of New Delhi. Known for strong academics, excellent placements, and strategic location in the capital."
    },
    {
        "id": 19,
        "name": "Indian Institute of Technology Kanpur",
        "short_name": "IIT Kanpur",
        "established": 1959,
        "type": "Government (Institute of National Importance)",
        "affiliation": "Autonomous (MHRD)",
        "accreditation": "NAAC A++, NIRF Top 5",
        "nirf_ranking": "4 (Engineering 2024)",
        "city": "Kanpur",
        "district": "Kanpur",
        "state": "Uttar Pradesh",
        "pincode": "208016",
        "address": "Kalyanpur, Kanpur - 208016",
        "courses_ug": "B.Tech CSE; B.Tech EE; B.Tech ME; B.Tech CE; B.Tech Chemical; B.Tech Aerospace; B.Tech MSE; B.Sc in 4 disciplines; Dual Degrees",
        "courses_pg": "M.Tech in 25+ specializations; MBA; M.Sc; M.Des",
        "courses_phd": "All departments",
        "fees_ug": "₹2 - ₹2.5 Lakhs per year",
        "fees_pg": "₹1.5 - ₹2 Lakhs per year",
        "fees_hostel": "₹25,000 - ₹40,000 per year",
        "fees_total_estimate": "₹10 - ₹12 Lakhs (4-year B.Tech)",
        "admission_ug": "Through JEE Advanced followed by JoSAA counselling.",
        "admission_pg": "GATE for M.Tech, CAT for MBA.",
        "admission_docs": "JEE Advanced Scorecard; Marksheets; Category Certificate",
        "admission_cutoff": "JEE Advanced: General - Top 600 (CSE)",
        "placement_avg": "₹20 LPA",
        "placement_highest": "₹1.8 Crore",
        "placement_median": "₹17 LPA",
        "placement_rate": "93%",
        "placement_recruiters": "Google; Microsoft; Amazon; Goldman Sachs; Flipkart; Samsung; Qualcomm; Adobe; Oracle; Tower Research",
        "facilities": "1000-acre campus; 12 Hostels; Airstrip; Sports Complex; Library; Hospital; Banks",
        "website": "https://www.iitk.ac.in",
        "phone": "+91-512-2590151",
        "email": "registrar@iitk.ac.in",
        "highlights": "Known for academic rigor; Has an airstrip on campus; Strong CS and EE departments; Pioneer of computer education in India",
        "description": "IIT Kanpur is renowned for its academic excellence and pioneering role in computer science education in India. Its 1000-acre campus near the Ganges is one of the largest IIT campuses."
    },
    {
        "id": 20,
        "name": "Indian Institute of Technology Kharagpur",
        "short_name": "IIT Kharagpur",
        "established": 1951,
        "type": "Government (Institute of National Importance)",
        "affiliation": "Autonomous (MHRD)",
        "accreditation": "NAAC A++, NIRF Top 5",
        "nirf_ranking": "5 (Engineering 2024)",
        "city": "Kharagpur",
        "district": "West Midnapore",
        "state": "West Bengal",
        "pincode": "721302",
        "address": "Kharagpur - 721302, West Bengal",
        "courses_ug": "B.Tech in 15+ branches; Dual Degree in 10+ branches; B.Arch; Integrated M.Sc",
        "courses_pg": "M.Tech in 40+ specializations; MBA; M.Sc; LLB; MBBS",
        "courses_phd": "All departments",
        "fees_ug": "₹2 - ₹2.5 Lakhs per year",
        "fees_pg": "₹1.5 - ₹2 Lakhs per year",
        "fees_hostel": "₹25,000 - ₹40,000 per year",
        "fees_total_estimate": "₹10 - ₹12 Lakhs (4-year B.Tech)",
        "admission_ug": "Through JEE Advanced followed by JoSAA counselling.",
        "admission_pg": "GATE for M.Tech, CAT for MBA.",
        "admission_docs": "JEE Advanced Scorecard; Marksheets; Category Certificate",
        "admission_cutoff": "JEE Advanced: General - Top 800 (CSE)",
        "placement_avg": "₹18 LPA",
        "placement_highest": "₹1.5 Crore",
        "placement_median": "₹15 LPA",
        "placement_rate": "91%",
        "placement_recruiters": "Google; Microsoft; Amazon; Goldman Sachs; Flipkart; Samsung; Apple; McKinsey; BCG",
        "facilities": "2100-acre campus (largest IIT); 22 Hostels; Hospital; Gymkhana; Sports Complex; Swimming Pool; Research Park; Banks; Market",
        "website": "https://www.iitkgp.ac.in",
        "phone": "+91-3222-255221",
        "email": "registrar@iitkgp.ac.in",
        "highlights": "India's first IIT (1951); Largest IIT campus (2100 acres); Offers Law and Medical programs; Spring Fest; 22 departments; Kshitij (tech fest)",
        "description": "IIT Kharagpur is India's first and largest IIT, established in 1951. Spread over 2100 acres, it offers the widest range of programs among IITs including Law and Medicine."
    },
    {
        "id": 21,
        "name": "Indian Institute of Technology Roorkee",
        "short_name": "IIT Roorkee",
        "established": 1847,
        "type": "Government (Institute of National Importance)",
        "affiliation": "Autonomous (MHRD)",
        "accreditation": "NAAC A++, NIRF Top 10",
        "nirf_ranking": "6 (Engineering 2024)",
        "city": "Roorkee",
        "district": "Haridwar",
        "state": "Uttarakhand",
        "pincode": "247667",
        "address": "Roorkee - 247667, Uttarakhand",
        "courses_ug": "B.Tech in 12 branches; B.Arch; Integrated M.Tech; Integrated M.Sc",
        "courses_pg": "M.Tech in 30+ specializations; MBA; M.Sc; MCA; M.Arch",
        "courses_phd": "All departments",
        "fees_ug": "₹2 - ₹2.5 Lakhs per year",
        "fees_pg": "₹1.5 - ₹2 Lakhs per year",
        "fees_hostel": "₹25,000 - ₹40,000 per year",
        "fees_total_estimate": "₹10 - ₹12 Lakhs (4-year B.Tech)",
        "admission_ug": "Through JEE Advanced followed by JoSAA counselling.",
        "admission_pg": "GATE for M.Tech, CAT for MBA.",
        "admission_docs": "JEE Advanced Scorecard; Marksheets; Category Certificate",
        "admission_cutoff": "JEE Advanced: General - Top 2000 (CSE)",
        "placement_avg": "₹17 LPA",
        "placement_highest": "₹1.5 Crore",
        "placement_median": "₹14 LPA",
        "placement_rate": "90%",
        "placement_recruiters": "Google; Microsoft; Amazon; Samsung; Qualcomm; Goldman Sachs; Adobe; Oracle; Flipkart",
        "facilities": "365-acre campus; Heritage buildings; 10 Hostels; Sports Complex; Library; Hospital",
        "website": "https://www.iitr.ac.in",
        "phone": "+91-1332-285311",
        "email": "registrar@iitr.ac.in",
        "highlights": "Asia's oldest technical institution (1847); Heritage campus; Strong civil engineering legacy; Cognizance (tech fest); Thomso (cultural fest)",
        "description": "IIT Roorkee, originally established in 1847 as Roorkee Engineering College, is Asia's oldest technical institution. Converted to IIT status in 2001, it combines heritage with modern excellence."
    },
    {
        "id": 22,
        "name": "Indian Institute of Technology Guwahati",
        "short_name": "IIT Guwahati",
        "established": 1994,
        "type": "Government (Institute of National Importance)",
        "affiliation": "Autonomous (MHRD)",
        "accreditation": "NAAC A++, NIRF Top 10",
        "nirf_ranking": "7 (Engineering 2024)",
        "city": "Guwahati",
        "district": "Kamrup",
        "state": "Assam",
        "pincode": "781039",
        "address": "North Guwahati - 781039, Assam",
        "courses_ug": "B.Tech CSE; B.Tech EE; B.Tech ME; B.Tech CE; B.Tech Chemical; B.Tech Biotech; B.Tech ECE; B.Des",
        "courses_pg": "M.Tech in 25+ specializations; MBA; M.Sc; M.Des; MA",
        "courses_phd": "All departments",
        "fees_ug": "₹2 - ₹2.5 Lakhs per year",
        "fees_pg": "₹1.5 - ₹2 Lakhs per year",
        "fees_hostel": "₹20,000 - ₹35,000 per year",
        "fees_total_estimate": "₹9 - ₹11 Lakhs (4-year B.Tech)",
        "admission_ug": "Through JEE Advanced followed by JoSAA counselling.",
        "admission_pg": "GATE for M.Tech, CAT for MBA.",
        "admission_docs": "JEE Advanced Scorecard; Marksheets; Category Certificate",
        "admission_cutoff": "JEE Advanced: General - Top 2500 (CSE)",
        "placement_avg": "₹16 LPA",
        "placement_highest": "₹1.2 Crore",
        "placement_median": "₹13 LPA",
        "placement_rate": "89%",
        "placement_recruiters": "Google; Microsoft; Amazon; Samsung; Qualcomm; Goldman Sachs; Adobe; Oracle",
        "facilities": "700-acre campus on Brahmaputra banks; 12 Hostels; Sports Complex; Lake; Hospital; Research Labs",
        "website": "https://www.iitg.ac.in",
        "phone": "+91-361-2583000",
        "email": "registrar@iitg.ac.in",
        "highlights": "Beautiful Brahmaputra riverside campus; Strong CSE department; Alcheringa (cultural fest); Techniche (tech fest); Northeast India's premier institution",
        "description": "IIT Guwahati is the premier technical institution in Northeast India, set on a beautiful 700-acre campus along the Brahmaputra river. Known for its scenic beauty and academic excellence."
    },
    {
        "id": 23,
        "name": "Indian Institute of Technology Hyderabad",
        "short_name": "IIT Hyderabad",
        "established": 2008,
        "type": "Government (Institute of National Importance)",
        "affiliation": "Autonomous (MHRD)",
        "accreditation": "NIRF Top 10",
        "nirf_ranking": "8 (Engineering 2024)",
        "city": "Hyderabad",
        "district": "Sangareddy",
        "state": "Telangana",
        "pincode": "502284",
        "address": "Kandi, Sangareddy - 502284, Telangana",
        "courses_ug": "B.Tech CSE; B.Tech EE; B.Tech ME; B.Tech CE; B.Tech Chemical; B.Tech MSE; B.Tech Biomedical; B.Tech AI",
        "courses_pg": "M.Tech in 20+ specializations; M.Des; M.Sc; MBA; MA",
        "courses_phd": "All departments",
        "fees_ug": "₹2 - ₹2.5 Lakhs per year",
        "fees_pg": "₹1.5 - ₹2 Lakhs per year",
        "fees_hostel": "₹25,000 - ₹40,000 per year",
        "fees_total_estimate": "₹10 - ₹12 Lakhs (4-year B.Tech)",
        "admission_ug": "Through JEE Advanced followed by JoSAA counselling.",
        "admission_pg": "GATE for M.Tech.",
        "admission_docs": "JEE Advanced Scorecard; Marksheets; Category Certificate",
        "admission_cutoff": "JEE Advanced: General - Top 3000 (CSE)",
        "placement_avg": "₹16 LPA",
        "placement_highest": "₹1.3 Crore",
        "placement_median": "₹13 LPA",
        "placement_rate": "90%",
        "placement_recruiters": "Google; Microsoft; Amazon; Goldman Sachs; Qualcomm; Samsung; Texas Instruments; Adobe",
        "facilities": "576-acre campus; Modern hostels; Research labs; Sports facilities; Hospital; Library",
        "website": "https://www.iith.ac.in",
        "phone": "+91-40-23016033",
        "email": "registrar@iith.ac.in",
        "highlights": "Newest IIT in top 10; B.Tech in AI (first in India); Strong research focus; Modern campus; Japan collaboration",
        "description": "IIT Hyderabad is one of India's fastest-growing IITs, known for pioneering the B.Tech in AI program and strong research collaborations with Japanese universities."
    },
    {
        "id": 24,
        "name": "Indian Institute of Technology (BHU) Varanasi",
        "short_name": "IIT BHU",
        "established": 1919,
        "type": "Government (Institute of National Importance)",
        "affiliation": "Autonomous (MHRD)",
        "accreditation": "NAAC A++, NIRF Top 15",
        "nirf_ranking": "11 (Engineering 2024)",
        "city": "Varanasi",
        "district": "Varanasi",
        "state": "Uttar Pradesh",
        "pincode": "221005",
        "address": "BHU Campus, Varanasi - 221005",
        "courses_ug": "B.Tech in 13 branches; IDD (Integrated Dual Degree) in 14 specializations",
        "courses_pg": "M.Tech in 20+ specializations; M.Sc; M.Pharm",
        "courses_phd": "All departments",
        "fees_ug": "₹2 - ₹2.5 Lakhs per year",
        "fees_pg": "₹1.5 - ₹2 Lakhs per year",
        "fees_hostel": "₹20,000 - ₹35,000 per year",
        "fees_total_estimate": "₹10 - ₹12 Lakhs (4-year B.Tech)",
        "admission_ug": "Through JEE Advanced followed by JoSAA counselling.",
        "admission_pg": "GATE for M.Tech.",
        "admission_docs": "JEE Advanced Scorecard; Marksheets; Category Certificate",
        "admission_cutoff": "JEE Advanced: General - Top 3500 (CSE)",
        "placement_avg": "₹15 LPA",
        "placement_highest": "₹1.2 Crore",
        "placement_median": "₹12 LPA",
        "placement_rate": "88%",
        "placement_recruiters": "Google; Microsoft; Amazon; Samsung; Goldman Sachs; Flipkart; Adobe; Oracle",
        "facilities": "Part of BHU (1300-acre campus); 10 Hostels; Temples; Hospital; Sports Complex; Library",
        "website": "https://www.iitbhu.ac.in",
        "phone": "+91-542-2369555",
        "email": "registrar@iitbhu.ac.in",
        "highlights": "Part of historic BHU campus; Integrated Dual Degree programs; Technex (tech fest); Rich heritage since 1919",
        "description": "IIT (BHU) Varanasi is part of the historic Banaras Hindu University campus. Originally established as BENCO in 1919, it combines over a century of engineering tradition with modern IIT excellence."
    },
    {
        "id": 25,
        "name": "Indian Institute of Technology Indore",
        "short_name": "IIT Indore",
        "established": 2009,
        "type": "Government (Institute of National Importance)",
        "affiliation": "Autonomous (MHRD)",
        "accreditation": "NIRF Top 15",
        "nirf_ranking": "13 (Engineering 2024)",
        "city": "Indore",
        "district": "Indore",
        "state": "Madhya Pradesh",
        "pincode": "453552",
        "address": "Simrol, Indore - 453552",
        "courses_ug": "B.Tech CSE; B.Tech EE; B.Tech ME; B.Tech CE; B.Tech Metallurgy",
        "courses_pg": "M.Tech in 10+ specializations; M.Sc; MBA",
        "courses_phd": "All departments",
        "fees_ug": "₹2 - ₹2.5 Lakhs per year",
        "fees_pg": "₹1.5 - ₹2 Lakhs per year",
        "fees_hostel": "₹25,000 - ₹40,000 per year",
        "fees_total_estimate": "₹10 - ₹12 Lakhs (4-year B.Tech)",
        "admission_ug": "Through JEE Advanced followed by JoSAA counselling.",
        "admission_pg": "GATE for M.Tech.",
        "admission_docs": "JEE Advanced Scorecard; Marksheets; Category Certificate",
        "admission_cutoff": "JEE Advanced: General - Top 4000 (CSE)",
        "placement_avg": "₹14 LPA",
        "placement_highest": "₹1.0 Crore",
        "placement_median": "₹12 LPA",
        "placement_rate": "87%",
        "placement_recruiters": "Google; Microsoft; Amazon; Samsung; Goldman Sachs; Qualcomm; Adobe",
        "facilities": "500-acre campus; Modern hostels; Research labs; Sports Complex; Library; Hospital",
        "website": "https://www.iiti.ac.in",
        "phone": "+91-731-6603100",
        "email": "registrar@iiti.ac.in",
        "highlights": "Fast-rising new IIT; Strong research output; Fluxus (tech fest); Modern campus infrastructure",
        "description": "IIT Indore is one of the fastest-rising new generation IITs, known for quality research and rapidly improving placements."
    },
    # ============================================================
    # MORE IITs + NITs (26-40)
    # ============================================================
    {
        "id": 26,
        "name": "Indian Institute of Technology Ropar",
        "short_name": "IIT Ropar",
        "established": 2008,
        "type": "Government (Institute of National Importance)",
        "affiliation": "Autonomous (MHRD)",
        "accreditation": "NIRF Top 25",
        "nirf_ranking": "20 (Engineering 2024)",
        "city": "Rupnagar",
        "district": "Rupnagar",
        "state": "Punjab",
        "pincode": "140001",
        "address": "Rupnagar - 140001, Punjab",
        "courses_ug": "B.Tech CSE; B.Tech EE; B.Tech ME; B.Tech CE; B.Tech Chemical; B.Tech Biomedical",
        "courses_pg": "M.Tech in 10+ specializations; M.Sc; MBA",
        "courses_phd": "All departments",
        "fees_ug": "₹2 - ₹2.5 Lakhs per year",
        "fees_pg": "₹1.5 - ₹2 Lakhs per year",
        "fees_hostel": "₹25,000 - ₹40,000 per year",
        "fees_total_estimate": "₹10 - ₹12 Lakhs (4-year B.Tech)",
        "admission_ug": "Through JEE Advanced followed by JoSAA counselling.",
        "admission_pg": "GATE for M.Tech.",
        "admission_docs": "JEE Advanced Scorecard; Marksheets; Category Certificate",
        "admission_cutoff": "JEE Advanced: General - Top 5000 (CSE)",
        "placement_avg": "₹14 LPA",
        "placement_highest": "₹80 LPA",
        "placement_median": "₹11 LPA",
        "placement_rate": "85%",
        "placement_recruiters": "Google; Microsoft; Amazon; Samsung; Goldman Sachs; Qualcomm",
        "facilities": "Modern campus; Hostels; Research labs; Sports; Library; Hospital",
        "website": "https://www.iitrpr.ac.in",
        "phone": "+91-1881-242100",
        "email": "registrar@iitrpr.ac.in",
        "highlights": "Fast-growing new IIT; ai4ICPS national hub; Strong CSE placements",
        "description": "IIT Ropar is a new-generation IIT in Punjab known for rapid growth and strong AI/ML research focus."
    },
    {
        "id": 27,
        "name": "National Institute of Technology Karnataka, Surathkal",
        "short_name": "NIT Surathkal",
        "established": 1960,
        "type": "Government (Institute of National Importance)",
        "affiliation": "Autonomous (MHRD)",
        "accreditation": "NAAC A++, NIRF Top 15",
        "nirf_ranking": "10 (Engineering 2024)",
        "city": "Mangalore",
        "district": "Dakshina Kannada",
        "state": "Karnataka",
        "pincode": "575025",
        "address": "Surathkal, Mangalore - 575025",
        "courses_ug": "B.Tech CSE; B.Tech ECE; B.Tech EE; B.Tech ME; B.Tech CE; B.Tech Chemical; B.Tech IT; B.Tech Metallurgy; B.Tech Mining",
        "courses_pg": "M.Tech in 20+ specializations; MBA; MCA; M.Sc",
        "courses_phd": "All departments",
        "fees_ug": "₹1.5 - ₹2 Lakhs per year",
        "fees_pg": "₹1 - ₹1.5 Lakhs per year",
        "fees_hostel": "₹20,000 - ₹35,000 per year",
        "fees_total_estimate": "₹8 - ₹10 Lakhs (4-year B.Tech)",
        "admission_ug": "Through JEE Main followed by JoSAA/CSAB counselling.",
        "admission_pg": "Through GATE score followed by CCMT counselling.",
        "admission_docs": "JEE Main Scorecard; Marksheets; Category Certificate",
        "admission_cutoff": "JEE Main: General - 8,000-12,000 rank (CSE)",
        "placement_avg": "₹14 LPA",
        "placement_highest": "₹1 Crore",
        "placement_median": "₹11 LPA",
        "placement_rate": "92%",
        "placement_recruiters": "Google; Microsoft; Amazon; Goldman Sachs; Samsung; Qualcomm; Flipkart; Oracle; Adobe",
        "facilities": "Beach campus; 300-acre campus; Hostels; Sports Complex; Swimming Pool; Library; Hospital",
        "website": "https://www.nitk.ac.in",
        "phone": "+91-824-2474000",
        "email": "registrar@nitk.ac.in",
        "highlights": "Top NIT in India; Beautiful beach campus; Engineer (tech fest); Strong alumni network in IT",
        "description": "NIT Karnataka Surathkal is consistently ranked as India's top NIT, located on a stunning beachside campus near Mangalore."
    },
    {
        "id": 28,
        "name": "National Institute of Technology Warangal",
        "short_name": "NIT Warangal",
        "established": 1959,
        "type": "Government (Institute of National Importance)",
        "affiliation": "Autonomous (MHRD)",
        "accreditation": "NAAC A++, NIRF Top 15",
        "nirf_ranking": "12 (Engineering 2024)",
        "city": "Warangal",
        "district": "Warangal",
        "state": "Telangana",
        "pincode": "506004",
        "address": "Warangal - 506004, Telangana",
        "courses_ug": "B.Tech CSE; B.Tech ECE; B.Tech EE; B.Tech ME; B.Tech CE; B.Tech Chemical; B.Tech Metallurgy; B.Tech Biotech",
        "courses_pg": "M.Tech in 20+ specializations; MBA; MCA; M.Sc",
        "courses_phd": "All departments",
        "fees_ug": "₹1.5 - ₹2 Lakhs per year",
        "fees_pg": "₹1 - ₹1.5 Lakhs per year",
        "fees_hostel": "₹20,000 - ₹30,000 per year",
        "fees_total_estimate": "₹8 - ₹10 Lakhs (4-year B.Tech)",
        "admission_ug": "Through JEE Main followed by JoSAA counselling.",
        "admission_pg": "Through GATE score followed by CCMT counselling.",
        "admission_docs": "JEE Main Scorecard; Marksheets; Category Certificate",
        "admission_cutoff": "JEE Main: General - 10,000-15,000 rank (CSE)",
        "placement_avg": "₹12 LPA",
        "placement_highest": "₹80 LPA",
        "placement_median": "₹10 LPA",
        "placement_rate": "90%",
        "placement_recruiters": "Google; Microsoft; Amazon; Goldman Sachs; Samsung; Oracle; Adobe; Flipkart",
        "facilities": "250-acre campus; Hostels; Sports Complex; Library; Hospital; Labs",
        "website": "https://www.nitw.ac.in",
        "phone": "+91-870-2462999",
        "email": "registrar@nitw.ac.in",
        "highlights": "One of the oldest NITs; Strong CSE and ECE; Technozion (tech fest); Great alumni network",
        "description": "NIT Warangal is one of India's premier NITs, known for strong engineering programs and excellent placements."
    },
    {
        "id": 29,
        "name": "National Institute of Technology Calicut",
        "short_name": "NIT Calicut",
        "established": 1961,
        "type": "Government (Institute of National Importance)",
        "affiliation": "Autonomous (MHRD)",
        "accreditation": "NAAC A+, NIRF Top 20",
        "nirf_ranking": "15 (Engineering 2024)",
        "city": "Kozhikode",
        "district": "Kozhikode",
        "state": "Kerala",
        "pincode": "673601",
        "address": "NIT Campus P.O., Kozhikode - 673601",
        "courses_ug": "B.Tech CSE; B.Tech ECE; B.Tech EE; B.Tech ME; B.Tech CE; B.Tech Chemical; B.Tech Biotech; B.Tech Production; B.Arch",
        "courses_pg": "M.Tech in 15+ specializations; MBA; MCA; M.Sc",
        "courses_phd": "All departments",
        "fees_ug": "₹1.5 - ₹2 Lakhs per year",
        "fees_pg": "₹1 - ₹1.5 Lakhs per year",
        "fees_hostel": "₹18,000 - ₹30,000 per year",
        "fees_total_estimate": "₹8 - ₹10 Lakhs (4-year B.Tech)",
        "admission_ug": "Through JEE Main followed by JoSAA counselling.",
        "admission_pg": "Through GATE score followed by CCMT counselling.",
        "admission_docs": "JEE Main Scorecard; Marksheets; Category Certificate",
        "admission_cutoff": "JEE Main: General - 12,000-18,000 rank (CSE)",
        "placement_avg": "₹10 LPA",
        "placement_highest": "₹60 LPA",
        "placement_median": "₹8 LPA",
        "placement_rate": "85%",
        "placement_recruiters": "Google; Microsoft; Amazon; TCS; Infosys; Flipkart; Oracle; Samsung",
        "facilities": "110-acre campus; Hostels; Sports Complex; Library; Hospital; Labs",
        "website": "https://www.nitc.ac.in",
        "phone": "+91-495-2286100",
        "email": "registrar@nitc.ac.in",
        "highlights": "Beautiful Kerala campus; Strong CSE program; Ragam (cultural fest); Tathva (tech fest)",
        "description": "NIT Calicut is a top NIT situated in the beautiful city of Kozhikode, Kerala, known for excellent CSE program and holistic development."
    },
    {
        "id": 30,
        "name": "National Institute of Technology Rourkela",
        "short_name": "NIT Rourkela",
        "established": 1961,
        "type": "Government (Institute of National Importance)",
        "affiliation": "Autonomous (MHRD)",
        "accreditation": "NAAC A+, NIRF Top 20",
        "nirf_ranking": "16 (Engineering 2024)",
        "city": "Rourkela",
        "district": "Sundargarh",
        "state": "Odisha",
        "pincode": "769008",
        "address": "NIT Rourkela - 769008, Odisha",
        "courses_ug": "B.Tech CSE; B.Tech ECE; B.Tech EE; B.Tech ME; B.Tech CE; B.Tech Chemical; B.Tech Metallurgy; B.Tech Mining; B.Tech Biotech; B.Tech Ceramic; B.Arch",
        "courses_pg": "M.Tech in 20+ specializations; MBA; MCA; M.Sc",
        "courses_phd": "All departments",
        "fees_ug": "₹1.5 - ₹2 Lakhs per year",
        "fees_pg": "₹1 - ₹1.5 Lakhs per year",
        "fees_hostel": "₹18,000 - ₹30,000 per year",
        "fees_total_estimate": "₹8 - ₹10 Lakhs (4-year B.Tech)",
        "admission_ug": "Through JEE Main followed by JoSAA counselling.",
        "admission_pg": "Through GATE score followed by CCMT counselling.",
        "admission_docs": "JEE Main Scorecard; Marksheets; Category Certificate",
        "admission_cutoff": "JEE Main: General - 13,000-20,000 rank (CSE)",
        "placement_avg": "₹10 LPA",
        "placement_highest": "₹50 LPA",
        "placement_median": "₹8 LPA",
        "placement_rate": "84%",
        "placement_recruiters": "Google; Microsoft; Amazon; TCS; Infosys; L&T; Samsung; Oracle",
        "facilities": "600-acre campus; 10 Hostels; Sports Complex; Library; Hospital; SAC",
        "website": "https://www.nitrkl.ac.in",
        "phone": "+91-661-2462999",
        "email": "registrar@nitrkl.ac.in",
        "highlights": "Among top NITs; Strong metallurgy and mining; Large campus; INNOVISION (tech fest)",
        "description": "NIT Rourkela is a premier NIT in Eastern India, known for metallurgy, mining, and a large 600-acre campus."
    },
    # ============================================================
    # TOP TAMIL NADU COLLEGES (31-45)
    # ============================================================
    {
        "id": 31,
        "name": "Anna University, College of Engineering Guindy",
        "short_name": "CEG Anna University",
        "established": 1794,
        "type": "Government (State University)",
        "affiliation": "Anna University (Autonomous)",
        "accreditation": "NAAC A++, NIRF Top 15",
        "nirf_ranking": "14 (University 2024)",
        "city": "Chennai",
        "district": "Chennai",
        "state": "Tamil Nadu",
        "pincode": "600025",
        "address": "Sardar Patel Road, Guindy, Chennai - 600025",
        "courses_ug": "B.E. CSE; B.E. ECE; B.E. EEE; B.E. Mechanical; B.E. Civil; B.E. Chemical; B.Tech IT; B.E. Manufacturing; B.E. Industrial; B.E. Mining; B.Arch",
        "courses_pg": "M.E./M.Tech in 30+ specializations; MBA; MCA; M.Sc; M.Arch",
        "courses_phd": "All departments",
        "fees_ug": "₹30,000 - ₹65,000 per year (Government quota)",
        "fees_pg": "₹35,000 - ₹70,000 per year",
        "fees_hostel": "₹12,000 - ₹20,000 per year",
        "fees_total_estimate": "₹2 - ₹4 Lakhs (4-year B.E.)",
        "admission_ug": "Through TNEA counselling based on HSC marks. Also accepts JEE Main.",
        "admission_pg": "Through TANCA counselling based on GATE/TANCET scores.",
        "admission_docs": "10th Marksheet; 12th Marksheet; Community Certificate; TC; Photos",
        "admission_cutoff": "TNEA Cutoff: OC - 195+/200 (CSE) - extremely competitive",
        "placement_avg": "₹8 LPA",
        "placement_highest": "₹42 LPA",
        "placement_median": "₹6 LPA",
        "placement_rate": "88%",
        "placement_recruiters": "Google; Microsoft; Amazon; Zoho; TCS; Infosys; Wipro; CTS; HCL; Oracle; Adobe; PayPal",
        "facilities": "100-acre campus in heart of Chennai; Central Library; Hostels; Guindy National Park adjacent; Research Labs; Sports Complex; Alumni Centre",
        "website": "https://www.annauniv.edu",
        "phone": "+91-44-22358585",
        "email": "registrar@annauniv.edu",
        "highlights": "One of Asia's oldest engineering colleges (1794); Mother university for TN engineering colleges; CEG campus in Guindy; Strong alumni network; Affordable government fees; Kurukshetra (tech fest)",
        "description": "College of Engineering Guindy (CEG) under Anna University is one of the oldest engineering colleges in Asia, established in 1794. Located in the heart of Chennai, it is the most prestigious engineering institution in Tamil Nadu."
    },
    {
        "id": 32,
        "name": "PSG College of Technology",
        "short_name": "PSG Tech Coimbatore",
        "established": 1951,
        "type": "Private (Aided - Autonomous)",
        "affiliation": "Anna University (Autonomous status)",
        "accreditation": "NAAC A++, NBA Accredited, NIRF Top 50",
        "nirf_ranking": "45 (Engineering 2024)",
        "city": "Coimbatore",
        "district": "Coimbatore",
        "state": "Tamil Nadu",
        "pincode": "641004",
        "address": "Peelamedu, Coimbatore - 641004",
        "courses_ug": "B.E. CSE; B.E. ECE; B.E. EEE; B.E. Mechanical; B.E. Automobile; B.E. Biomedical; B.E. Robotics; B.Tech IT; B.Tech Textile; B.E. Production; B.E. Metallurgy",
        "courses_pg": "M.E./M.Tech in 15+ specializations; MBA; MCA; M.Sc",
        "courses_phd": "All departments",
        "fees_ug": "₹75,000 - ₹1,25,000 per year",
        "fees_pg": "₹50,000 - ₹85,000 per year",
        "fees_hostel": "₹45,000 - ₹65,000 per year",
        "fees_total_estimate": "₹4 - ₹6 Lakhs (4-year B.E.)",
        "admission_ug": "Through TNEA counselling. Very high cutoffs required.",
        "admission_pg": "Through TANCA counselling based on GATE/TANCET.",
        "admission_docs": "10th Marksheet; 12th Marksheet; Community Certificate; TC; Photos",
        "admission_cutoff": "TNEA Cutoff: OC - 196+/200 (CSE) - among highest in TN",
        "placement_avg": "₹7 LPA",
        "placement_highest": "₹45 LPA",
        "placement_median": "₹5.5 LPA",
        "placement_rate": "90%",
        "placement_recruiters": "Google; Amazon; Zoho; TCS; Infosys; CTS; Robert Bosch; Caterpillar; L&T; Ford; Hyundai",
        "facilities": "45-acre campus; Central Library; Hostels; PSG Hospitals; Sports Complex; IEEE Student Branch; Innovation Lab; Workshops",
        "website": "https://www.psgtech.edu",
        "phone": "+91-422-2572177",
        "email": "principal@psgtech.edu",
        "highlights": "Among top 3 engineering colleges in TN; PSG Group (strong industrial backing); Known for core engineering; Very selective admissions; Strong industry connections in Coimbatore manufacturing hub",
        "description": "PSG College of Technology is one of Tamil Nadu's most prestigious private engineering colleges, backed by the PSG industrial conglomerate. Known for exceptional core engineering education and industry connections."
    },
    {
        "id": 33,
        "name": "Vellore Institute of Technology",
        "short_name": "VIT Vellore",
        "established": 1984,
        "type": "Private (Deemed University)",
        "affiliation": "Deemed University (UGC)",
        "accreditation": "NAAC A++, NIRF Top 15",
        "nirf_ranking": "11 (Engineering 2024)",
        "city": "Vellore",
        "district": "Vellore",
        "state": "Tamil Nadu",
        "pincode": "632014",
        "address": "VIT Vellore - 632014, Tamil Nadu",
        "courses_ug": "B.Tech CSE; B.Tech CSE (AI/ML); B.Tech CSE (Data Science); B.Tech CSE (Cyber Security); B.Tech ECE; B.Tech EEE; B.Tech ME; B.Tech CE; B.Tech Biotech; B.Tech Chemical; B.Arch; 30+ specializations",
        "courses_pg": "M.Tech in 25+ specializations; MBA; MCA; M.Sc; M.Des",
        "courses_phd": "All departments",
        "fees_ug": "₹2 - ₹3.5 Lakhs per year (varies by category)",
        "fees_pg": "₹1 - ₹2 Lakhs per year (MBA: ₹8 Lakhs total)",
        "fees_hostel": "₹1 - ₹1.5 Lakhs per year",
        "fees_total_estimate": "₹12 - ₹18 Lakhs (4-year B.Tech)",
        "admission_ug": "Through VITEEE (VIT Engineering Entrance Exam) conducted in April. Apply online.",
        "admission_pg": "Through VITMEE or GATE score.",
        "admission_docs": "VITEEE Scorecard; 10th & 12th Marksheets; TC; Photos; Aadhar",
        "admission_cutoff": "VITEEE rank-based counselling. Top ranks get preferred branches.",
        "placement_avg": "₹8 LPA",
        "placement_highest": "₹52 LPA",
        "placement_median": "₹6.5 LPA",
        "placement_rate": "88%",
        "placement_recruiters": "Microsoft; Amazon; Google; Deloitte; Goldman Sachs; TCS; Infosys; Wipro; Cognizant; Zoho; Accenture; Capgemini; IBM; SAP",
        "facilities": "350-acre campus; AC Hostels; International Standard Labs; Swimming Pool; Gym; Food Court; Hospital; ATM; Shopping; Auditorium; Recording Studio",
        "website": "https://www.vit.ac.in",
        "phone": "+91-416-2202157",
        "email": "admissions@vit.ac.in",
        "highlights": "NIRF #11; Deemed University; Multiple campuses (Vellore, Chennai, AP, Bhopal); VITEEE conducted for 2.5 lakh+ students; International collaborations with 200+ universities; Riviera (cultural fest); GravITas (tech fest)",
        "description": "VIT Vellore is one of India's top private engineering universities, known for excellent placements, world-class infrastructure, and a globally recognized degree. It attracts students from 60+ countries."
    },
    {
        "id": 34,
        "name": "SRM Institute of Science and Technology, Kattankulathur",
        "short_name": "SRM Chennai",
        "established": 1985,
        "type": "Private (Deemed University)",
        "affiliation": "Deemed University (UGC)",
        "accreditation": "NAAC A++, NIRF Top 40",
        "nirf_ranking": "36 (University 2024)",
        "city": "Kattankulathur",
        "district": "Chengalpattu",
        "state": "Tamil Nadu",
        "pincode": "603203",
        "address": "SRM Nagar, Kattankulathur - 603203",
        "courses_ug": "B.Tech in 40+ specializations including CSE, AI, Data Science, ECE, ME, CE, Biotech, Nanotechnology, Genetic Engineering",
        "courses_pg": "M.Tech in 25+ specializations; MBA; MCA; M.Sc; M.Arch",
        "courses_phd": "All departments",
        "fees_ug": "₹2 - ₹3.5 Lakhs per year",
        "fees_pg": "₹1.5 - ₹2.5 Lakhs per year",
        "fees_hostel": "₹1 - ₹1.5 Lakhs per year",
        "fees_total_estimate": "₹12 - ₹18 Lakhs (4-year B.Tech)",
        "admission_ug": "Through SRMJEEE conducted in April-May. Online test.",
        "admission_pg": "Through SRM entrance exam or GATE score.",
        "admission_docs": "SRMJEEE Scorecard; 10th & 12th Marksheets; TC; Photos; Aadhar",
        "admission_cutoff": "SRMJEEE rank-based counselling",
        "placement_avg": "₹7 LPA",
        "placement_highest": "₹41 LPA",
        "placement_median": "₹5 LPA",
        "placement_rate": "85%",
        "placement_recruiters": "Amazon; Google; Microsoft; TCS; Infosys; Wipro; CTS; HCL; Accenture; Zoho; IBM; L&T; Hyundai",
        "facilities": "250-acre campus; AC Hostels; Hospital; Sports Complex; Swimming Pool; Gym; Labs; Library; Food Courts; Banks; Medical College on campus",
        "website": "https://www.srmist.edu.in",
        "phone": "+91-44-27452000",
        "email": "admissions@srmist.edu.in",
        "highlights": "One of India's largest private universities; NAAC A++; Multiple campuses; Own Medical College and Hospital; Milan (cultural fest); Strong international tie-ups",
        "description": "SRM Institute of Science and Technology is one of India's largest and most well-known private universities, headquartered in Chennai with multiple campuses across India."
    },
    {
        "id": 35,
        "name": "Thiagarajar College of Engineering",
        "short_name": "TCE Madurai",
        "established": 1957,
        "type": "Private (Aided - Autonomous)",
        "affiliation": "Anna University (Autonomous)",
        "accreditation": "NAAC A+, NBA Accredited, NIRF Top 100",
        "nirf_ranking": "72 (Engineering 2024)",
        "city": "Madurai",
        "district": "Madurai",
        "state": "Tamil Nadu",
        "pincode": "625015",
        "address": "Thiruparankundram, Madurai - 625015",
        "courses_ug": "B.E. CSE; B.E. ECE; B.E. EEE; B.E. Mechanical; B.E. Civil; B.Tech IT; B.E. ICE",
        "courses_pg": "M.E. CSE; M.E. Communication Systems; M.E. CAD/CAM; MBA; MCA",
        "courses_phd": "All departments",
        "fees_ug": "₹60,000 - ₹1,00,000 per year",
        "fees_pg": "₹45,000 - ₹75,000 per year",
        "fees_hostel": "₹40,000 - ₹60,000 per year",
        "fees_total_estimate": "₹3.5 - ₹5 Lakhs (4-year B.E.)",
        "admission_ug": "Through TNEA counselling. Very competitive cutoffs.",
        "admission_pg": "Through TANCA counselling.",
        "admission_docs": "10th Marksheet; 12th Marksheet; Community Certificate; TC; Photos",
        "admission_cutoff": "TNEA Cutoff: OC - 193+/200 (CSE)",
        "placement_avg": "₹5.5 LPA",
        "placement_highest": "₹20 LPA",
        "placement_median": "₹4.5 LPA",
        "placement_rate": "85%",
        "placement_recruiters": "Zoho; TCS; Infosys; Wipro; CTS; Amazon; Accenture; L&T; Ashok Leyland",
        "facilities": "Library; Hostels; Sports Complex; Labs; WiFi; Canteen; Auditorium; NCC; NSS",
        "website": "https://www.tce.edu",
        "phone": "+91-452-2482240",
        "email": "principal@tce.edu",
        "highlights": "One of TN's best autonomous colleges; Strong Zoho recruiter; Affordable; Excellent academics; NIRF ranked",
        "description": "Thiagarajar College of Engineering is one of Tamil Nadu's most respected autonomous engineering colleges, known for academic excellence and strong Zoho placements in Madurai."
    },
    {
        "id": 36,
        "name": "Kongu Engineering College",
        "short_name": "KEC Erode",
        "established": 1984,
        "type": "Private (Aided - Autonomous)",
        "affiliation": "Anna University (Autonomous)",
        "accreditation": "NAAC A+, NBA Accredited, NIRF Top 100",
        "nirf_ranking": "89 (Engineering 2024)",
        "city": "Erode",
        "district": "Erode",
        "state": "Tamil Nadu",
        "pincode": "638060",
        "address": "Perundurai, Erode - 638060",
        "courses_ug": "B.E. CSE; B.E. ECE; B.E. EEE; B.E. Mechanical; B.E. Civil; B.Tech IT; B.E. AI&DS; B.E. Biotech; B.E. Automobile; B.E. Food Technology",
        "courses_pg": "M.E. CSE; M.E. VLSI; M.E. CAD/CAM; MBA; MCA",
        "courses_phd": "All departments",
        "fees_ug": "₹70,000 - ₹1,10,000 per year",
        "fees_pg": "₹50,000 - ₹80,000 per year",
        "fees_hostel": "₹45,000 - ₹65,000 per year",
        "fees_total_estimate": "₹3.5 - ₹5 Lakhs (4-year B.E.)",
        "admission_ug": "Through TNEA counselling.",
        "admission_pg": "Through TANCA counselling.",
        "admission_docs": "10th Marksheet; 12th Marksheet; Community Certificate; TC; Photos",
        "admission_cutoff": "TNEA Cutoff: OC - 190+/200 (CSE)",
        "placement_avg": "₹5 LPA",
        "placement_highest": "₹18 LPA",
        "placement_median": "₹4.2 LPA",
        "placement_rate": "82%",
        "placement_recruiters": "Zoho; TCS; Infosys; Wipro; CTS; HCL; Accenture; L&T; Caterpillar",
        "facilities": "75-acre campus; Library; Hostels; Sports; Labs; WiFi; Canteen; Auditorium",
        "website": "https://www.kongu.ac.in",
        "phone": "+91-4294-226000",
        "email": "principal@kongu.edu",
        "highlights": "Top autonomous college in Western TN; NAAC A+; Strong placements; Agriculture belt location; Affordable",
        "description": "Kongu Engineering College is a top-rated autonomous engineering college in Erode, known for its disciplined academic environment and strong placement record."
    },
    {
        "id": 37,
        "name": "SSN College of Engineering",
        "short_name": "SSN Chennai",
        "established": 1996,
        "type": "Private (Autonomous)",
        "affiliation": "Anna University (Autonomous)",
        "accreditation": "NAAC A+, NBA Accredited, NIRF Top 50",
        "nirf_ranking": "40 (Engineering 2024)",
        "city": "Chennai",
        "district": "Chennai",
        "state": "Tamil Nadu",
        "pincode": "603110",
        "address": "Kalavakkam, Old Mahabalipuram Road, Chennai - 603110",
        "courses_ug": "B.E. CSE; B.E. ECE; B.E. EEE; B.E. Mechanical; B.E. Civil; B.Tech IT; B.E. BME; B.E. Chemical",
        "courses_pg": "M.E. CSE; M.E. VLSI; M.E. Communication; M.E. Applied Electronics; MBA",
        "courses_phd": "All departments",
        "fees_ug": "₹1.5 - ₹2 Lakhs per year",
        "fees_pg": "₹75,000 - ₹1.2 Lakhs per year",
        "fees_hostel": "₹80,000 - ₹1.2 Lakhs per year",
        "fees_total_estimate": "₹8 - ₹10 Lakhs (4-year B.E.)",
        "admission_ug": "Through TNEA counselling. Among highest cutoffs after CEG.",
        "admission_pg": "Through TANCA counselling.",
        "admission_docs": "10th Marksheet; 12th Marksheet; Community Certificate; TC; Photos",
        "admission_cutoff": "TNEA Cutoff: OC - 197+/200 (CSE) - extremely competitive",
        "placement_avg": "₹8.5 LPA",
        "placement_highest": "₹44 LPA",
        "placement_median": "₹7 LPA",
        "placement_rate": "92%",
        "placement_recruiters": "Google; Microsoft; Amazon; Goldman Sachs; Zoho; TCS; Infosys; Oracle; Adobe; PayPal; Flipkart",
        "facilities": "200-acre campus; Modern Library; AC Hostels; Auditorium; Labs; Sports Complex; Cafeteria; Smart Classrooms",
        "website": "https://www.ssn.edu.in",
        "phone": "+91-44-27469700",
        "email": "principal@ssn.edu.in",
        "highlights": "Founded by SSN Trust (Dr. Shiv Nadar - HCL); Among best private colleges in TN; Extremely high TNEA cutoffs; Premium campus; Strong research focus",
        "description": "SSN College of Engineering, founded by HCL's Dr. Shiv Nadar, is regarded as the best private engineering college in Tamil Nadu with exceptional placements and world-class infrastructure."
    },
    {
        "id": 38,
        "name": "Coimbatore Institute of Technology",
        "short_name": "CIT Coimbatore",
        "established": 1956,
        "type": "Government (Autonomous)",
        "affiliation": "Anna University (Autonomous)",
        "accreditation": "NAAC A+, NBA Accredited",
        "nirf_ranking": "101-150 (Engineering)",
        "city": "Coimbatore",
        "district": "Coimbatore",
        "state": "Tamil Nadu",
        "pincode": "641014",
        "address": "Avinashi Road, Coimbatore - 641014",
        "courses_ug": "B.E. CSE; B.E. ECE; B.E. EEE; B.E. Mechanical; B.E. Civil; B.Tech IT; B.Tech Chemical",
        "courses_pg": "M.E. CSE; M.E. VLSI; M.E. Structural; MBA",
        "courses_phd": "CSE; ECE; Mechanical; Civil",
        "fees_ug": "₹25,000 - ₹55,000 per year (Government)",
        "fees_pg": "₹30,000 - ₹60,000 per year",
        "fees_hostel": "₹12,000 - ₹20,000 per year",
        "fees_total_estimate": "₹1.5 - ₹3 Lakhs (4-year B.E.)",
        "admission_ug": "Through TNEA counselling.",
        "admission_pg": "Through TANCA counselling.",
        "admission_docs": "10th Marksheet; 12th Marksheet; Community Certificate; TC; Photos",
        "admission_cutoff": "TNEA Cutoff: OC - 192+/200 (CSE)",
        "placement_avg": "₹5.5 LPA",
        "placement_highest": "₹22 LPA",
        "placement_median": "₹4.5 LPA",
        "placement_rate": "80%",
        "placement_recruiters": "Zoho; TCS; Infosys; CTS; Wipro; Accenture; L&T; Caterpillar; Ford",
        "facilities": "Library; Hostels; Sports; Labs; WiFi; Canteen; Workshops",
        "website": "https://www.cit.edu.in",
        "phone": "+91-422-2574071",
        "email": "principal@cit.edu.in",
        "highlights": "One of TN's oldest govt colleges; Autonomous status; Very affordable; Strong mechanical and civil departments; Coimbatore manufacturing hub",
        "description": "Coimbatore Institute of Technology is one of Tamil Nadu's oldest and most respected government engineering colleges, known for affordable education and strong core engineering."
    },
    {
        "id": 39,
        "name": "Government College of Technology, Coimbatore",
        "short_name": "GCT Coimbatore",
        "established": 1945,
        "type": "Government (Autonomous)",
        "affiliation": "Anna University (Autonomous)",
        "accreditation": "NAAC A, NBA Accredited",
        "nirf_ranking": "101-150 (Engineering)",
        "city": "Coimbatore",
        "district": "Coimbatore",
        "state": "Tamil Nadu",
        "pincode": "641013",
        "address": "Thadagam Road, Coimbatore - 641013",
        "courses_ug": "B.E. CSE; B.E. ECE; B.E. EEE; B.E. Mechanical; B.E. Civil; B.E. Production; B.Tech Textile; B.Tech IT",
        "courses_pg": "M.E. CSE; M.E. CAD/CAM; M.E. Structural; MBA",
        "courses_phd": "All departments",
        "fees_ug": "₹20,000 - ₹50,000 per year (Government)",
        "fees_pg": "₹25,000 - ₹55,000 per year",
        "fees_hostel": "₹10,000 - ₹18,000 per year",
        "fees_total_estimate": "₹1 - ₹2.5 Lakhs (4-year B.E.)",
        "admission_ug": "Through TNEA counselling.",
        "admission_pg": "Through TANCA counselling.",
        "admission_docs": "10th Marksheet; 12th Marksheet; Community Certificate; TC; Photos",
        "admission_cutoff": "TNEA Cutoff: OC - 190+/200 (CSE)",
        "placement_avg": "₹4.5 LPA",
        "placement_highest": "₹15 LPA",
        "placement_median": "₹3.8 LPA",
        "placement_rate": "75%",
        "placement_recruiters": "TCS; Infosys; Wipro; CTS; HCL; L&T; Caterpillar",
        "facilities": "Heritage campus; Library; Hostels; Sports; Labs; Workshops; Canteen",
        "website": "https://www.gct.ac.in",
        "phone": "+91-422-2432221",
        "email": "principal@gct.ac.in",
        "highlights": "One of TN's oldest engineering colleges (1945); Heritage campus; Extremely affordable; Strong alumni network",
        "description": "Government College of Technology Coimbatore is one of the oldest and most respected government engineering colleges in Tamil Nadu, established in 1945."
    },
    {
        "id": 40,
        "name": "Kumaraguru College of Technology",
        "short_name": "KCT Coimbatore",
        "established": 1984,
        "type": "Private (Autonomous)",
        "affiliation": "Anna University (Autonomous)",
        "accreditation": "NAAC A+, NBA Accredited",
        "nirf_ranking": "101-150 (Engineering)",
        "city": "Coimbatore",
        "district": "Coimbatore",
        "state": "Tamil Nadu",
        "pincode": "641049",
        "address": "Chinnavedampatti, Coimbatore - 641049",
        "courses_ug": "B.E. CSE; B.E. ECE; B.E. EEE; B.E. Mechanical; B.E. Civil; B.Tech IT; B.E. AI&DS; B.Tech Biotech; B.E. Automobile",
        "courses_pg": "M.E. CSE; M.E. VLSI; MBA; M.Sc",
        "courses_phd": "CSE; ECE; Mechanical",
        "fees_ug": "₹1 - ₹1.5 Lakhs per year",
        "fees_pg": "₹60,000 - ₹1 Lakh per year",
        "fees_hostel": "₹60,000 - ₹90,000 per year",
        "fees_total_estimate": "₹5 - ₹7 Lakhs (4-year B.E.)",
        "admission_ug": "Through TNEA counselling.",
        "admission_pg": "Through TANCA counselling.",
        "admission_docs": "10th Marksheet; 12th Marksheet; Community Certificate; TC; Photos",
        "admission_cutoff": "TNEA Cutoff: OC - 190+/200 (CSE)",
        "placement_avg": "₹5.5 LPA",
        "placement_highest": "₹25 LPA",
        "placement_median": "₹4.5 LPA",
        "placement_rate": "83%",
        "placement_recruiters": "Zoho; TCS; Infosys; CTS; Wipro; Accenture; Amazon; Bosch; L&T",
        "facilities": "Library; Hostels; Sports Complex; Labs; Innovation Centre; Cafeteria; Auditorium",
        "website": "https://www.kct.ac.in",
        "phone": "+91-422-2669401",
        "email": "principal@kct.ac.in",
        "highlights": "KCT Innovation Lab; NAAC A+; Strong industry partnerships; Good placements; Modern campus",
        "description": "Kumaraguru College of Technology is a premier autonomous engineering college in Coimbatore known for innovation, industry connections, and consistent placements."
    },
    {
        "id": 41,
        "name": "SASTRA Deemed University",
        "short_name": "SASTRA Thanjavur",
        "established": 1984,
        "type": "Private (Deemed University)",
        "affiliation": "Deemed University (UGC)",
        "accreditation": "NAAC A++, NIRF Top 30",
        "nirf_ranking": "28 (Engineering 2024)",
        "city": "Thanjavur",
        "district": "Thanjavur",
        "state": "Tamil Nadu",
        "pincode": "613401",
        "address": "Tirumalaisamudram, Thanjavur - 613401",
        "courses_ug": "B.Tech CSE; B.Tech ECE; B.Tech EEE; B.Tech ME; B.Tech CE; B.Tech AI&DS; B.Tech Biotech; B.Tech Chemical; B.Tech ICE; B.Tech Nanotechnology; B.Arch; BBA; BCA",
        "courses_pg": "M.Tech in 15+ specializations; MBA; MCA; M.Sc; M.Pharm; LLM",
        "courses_phd": "All departments",
        "fees_ug": "₹1.5 - ₹2.5 Lakhs per year",
        "fees_pg": "₹1 - ₹1.5 Lakhs per year",
        "fees_hostel": "₹60,000 - ₹90,000 per year",
        "fees_total_estimate": "₹8 - ₹12 Lakhs (4-year B.Tech)",
        "admission_ug": "Through SASTRA entrance exam or JEE Main score.",
        "admission_pg": "Through GATE or SASTRA entrance exam.",
        "admission_docs": "Entrance Exam Score; 10th & 12th Marksheets; TC; Photos; Aadhar",
        "admission_cutoff": "Merit-based through entrance exam",
        "placement_avg": "₹6.5 LPA",
        "placement_highest": "₹35 LPA",
        "placement_median": "₹5 LPA",
        "placement_rate": "86%",
        "placement_recruiters": "Amazon; Google; Microsoft; TCS; Infosys; CTS; Wipro; Zoho; L&T; Bosch; Oracle",
        "facilities": "100-acre campus; Central Library; Hostels; Sports Complex; Research Labs; Hospital; Auditorium; Banks; Shopping",
        "website": "https://www.sastra.edu",
        "phone": "+91-4362-264101",
        "email": "admissions@sastra.edu",
        "highlights": "NIRF #28; Deemed University; Near Trichy; Very strong academically; Law and Pharmacy programs too; Research focus; Good ROI",
        "description": "SASTRA Deemed University is one of South India's top deemed universities near Tiruchirappalli, known for disciplined academics, strong placements, and diverse programs."
    },
    {
        "id": 42,
        "name": "Amrita Vishwa Vidyapeetham, Coimbatore",
        "short_name": "Amrita Coimbatore",
        "established": 2003,
        "type": "Private (Deemed University)",
        "affiliation": "Deemed University (UGC)",
        "accreditation": "NAAC A++, NIRF Top 10",
        "nirf_ranking": "7 (University 2024)",
        "city": "Coimbatore",
        "district": "Coimbatore",
        "state": "Tamil Nadu",
        "pincode": "641112",
        "address": "Ettimadai, Coimbatore - 641112",
        "courses_ug": "B.Tech CSE; B.Tech AI; B.Tech ECE; B.Tech EEE; B.Tech ME; B.Tech CE; B.Tech Chemical; B.Tech Aerospace; B.Tech Biomedical",
        "courses_pg": "M.Tech in 20+ specializations; MBA; MCA; M.Sc",
        "courses_phd": "All departments",
        "fees_ug": "₹2 - ₹3 Lakhs per year",
        "fees_pg": "₹1 - ₹2 Lakhs per year",
        "fees_hostel": "₹80,000 - ₹1.2 Lakhs per year",
        "fees_total_estimate": "₹10 - ₹15 Lakhs (4-year B.Tech)",
        "admission_ug": "Through AEEE (Amrita Engineering Entrance Exam) in January.",
        "admission_pg": "Through GATE or Amrita entrance exam.",
        "admission_docs": "AEEE Scorecard; 10th & 12th Marksheets; TC; Photos",
        "admission_cutoff": "AEEE rank-based counselling",
        "placement_avg": "₹7.5 LPA",
        "placement_highest": "₹40 LPA",
        "placement_median": "₹6 LPA",
        "placement_rate": "87%",
        "placement_recruiters": "Google; Microsoft; Amazon; Goldman Sachs; TCS; Infosys; CTS; Zoho; Oracle; Adobe; Samsung",
        "facilities": "450-acre campus in Western Ghats foothills; Hostels; Research Labs; Hospital; Sports Complex; Meditation Centre; Library",
        "website": "https://www.amrita.edu",
        "phone": "+91-422-2685000",
        "email": "admissions@amrita.edu",
        "highlights": "NIRF Top 10 University; Founded by Amma (Mata Amritanandamayi); Beautiful campus in Western Ghats; Strong research; Values-based education; 7 campuses across India",
        "description": "Amrita Vishwa Vidyapeetham is a NIRF Top 10 deemed university with a beautiful 450-acre campus in the Western Ghats foothills near Coimbatore. Known for value-based education and strong research."
    },
    {
        "id": 43,
        "name": "Madras Institute of Technology",
        "short_name": "MIT Anna University",
        "established": 1949,
        "type": "Government (State University)",
        "affiliation": "Anna University",
        "accreditation": "NAAC A++",
        "nirf_ranking": "Part of Anna University ranking",
        "city": "Chennai",
        "district": "Chennai",
        "state": "Tamil Nadu",
        "pincode": "600044",
        "address": "Chromepet, Chennai - 600044",
        "courses_ug": "B.E. Automobile; B.E. Electronics; B.E. Rubber & Plastics; B.Tech Chemical; B.Tech IT; B.E. Production; B.E. Instrumentation",
        "courses_pg": "M.E. in specialized tracks; M.Tech",
        "courses_phd": "All departments",
        "fees_ug": "₹25,000 - ₹55,000 per year (Government)",
        "fees_pg": "₹30,000 - ₹60,000 per year",
        "fees_hostel": "₹10,000 - ₹18,000 per year",
        "fees_total_estimate": "₹1.5 - ₹3 Lakhs (4-year B.E.)",
        "admission_ug": "Through TNEA counselling.",
        "admission_pg": "Through TANCA counselling.",
        "admission_docs": "10th Marksheet; 12th Marksheet; Community Certificate; TC; Photos",
        "admission_cutoff": "TNEA Cutoff: OC - 190+/200",
        "placement_avg": "₹6 LPA",
        "placement_highest": "₹25 LPA",
        "placement_median": "₹5 LPA",
        "placement_rate": "82%",
        "placement_recruiters": "TCS; Infosys; CTS; Wipro; L&T; Hyundai; Ashok Leyland; TVS; Ford",
        "facilities": "Heritage campus; Library; Hostels; Labs; Sports; Workshops; Canteen",
        "website": "https://www.mitindia.edu",
        "phone": "+91-44-22516700",
        "email": "principal@mitindia.edu",
        "highlights": "Where Dr. APJ Abdul Kalam studied; Pioneer of automobile engineering in India; Heritage institution; Part of Anna University; Very affordable",
        "description": "Madras Institute of Technology is a legendary institution where former President Dr. APJ Abdul Kalam studied. It pioneered automobile engineering education in India and is part of Anna University."
    },
    {
        "id": 44,
        "name": "Sri Sivasubramaniya Nadar College of Engineering",
        "short_name": "SSN College of Engineering",
        "established": 1996,
        "type": "Private (Self-Financing - Autonomous)",
        "affiliation": "Anna University (Autonomous)",
        "accreditation": "NAAC A+, NBA Accredited",
        "nirf_ranking": "40 (Engineering 2024)",
        "city": "Chennai",
        "district": "Kancheepuram",
        "state": "Tamil Nadu",
        "pincode": "603110",
        "address": "Kalavakkam, OMR, Chennai - 603110",
        "courses_ug": "B.E. CSE; B.E. ECE; B.E. EEE; B.E. Mechanical; B.E. Civil; B.Tech IT; B.E. Biomedical; B.E. Chemical",
        "courses_pg": "M.E. CSE; M.E. Communication Systems; M.E. VLSI; M.E. Applied Electronics; MBA",
        "courses_phd": "All departments",
        "fees_ug": "₹1.5 - ₹2 Lakhs per year",
        "fees_pg": "₹80,000 - ₹1.2 Lakhs per year",
        "fees_hostel": "₹80,000 - ₹1.2 Lakhs per year",
        "fees_total_estimate": "₹8 - ₹10 Lakhs (4-year B.E.)",
        "admission_ug": "Through TNEA counselling. Management quota also available.",
        "admission_pg": "Through TANCA counselling.",
        "admission_docs": "10th Marksheet; 12th Marksheet; Community Certificate; TC; Photos",
        "admission_cutoff": "TNEA Cutoff: OC - 197+/200 (CSE)",
        "placement_avg": "₹8.5 LPA",
        "placement_highest": "₹44 LPA",
        "placement_median": "₹7 LPA",
        "placement_rate": "92%",
        "placement_recruiters": "Google; Microsoft; Amazon; Goldman Sachs; Zoho; PayPal; TCS; Oracle; Adobe; Samsung; Flipkart",
        "facilities": "200-acre campus; Modern Library; AC Labs; Hostels; Sports Complex; Innovation Hub; Auditorium; Cafeteria",
        "website": "https://www.ssn.edu.in",
        "phone": "+91-44-27469700",
        "email": "principal@ssn.edu.in",
        "highlights": "Founded by SSN Trust (HCL's Shiv Nadar); Best private engineering college in TN; Highest TNEA cutoffs among private colleges; Invente (tech fest); Research focus",
        "description": "SSN College of Engineering, established by HCL founder Shiv Nadar's trust, is widely regarded as the best private engineering college in Tamil Nadu with unmatched placement records."
    },
    {
        "id": 45,
        "name": "Vel Tech Rangarajan Dr. Sagunthala R&D Institute of Science and Technology",
        "short_name": "Vel Tech Chennai",
        "established": 1997,
        "type": "Private (Deemed University)",
        "affiliation": "Deemed University (UGC)",
        "accreditation": "NAAC A+, NIRF Top 100",
        "nirf_ranking": "68 (Engineering 2024)",
        "city": "Chennai",
        "district": "Chennai",
        "state": "Tamil Nadu",
        "pincode": "600062",
        "address": "Avadi, Chennai - 600062",
        "courses_ug": "B.Tech CSE; B.Tech AI; B.Tech ECE; B.Tech EEE; B.Tech ME; B.Tech CE; B.Tech Aerospace; B.Arch; B.Tech Biotech",
        "courses_pg": "M.Tech in 15+ specializations; MBA; MCA; M.Sc",
        "courses_phd": "All departments",
        "fees_ug": "₹1.2 - ₹2 Lakhs per year",
        "fees_pg": "₹80,000 - ₹1.2 Lakhs per year",
        "fees_hostel": "₹60,000 - ₹90,000 per year",
        "fees_total_estimate": "₹6 - ₹10 Lakhs (4-year B.Tech)",
        "admission_ug": "Through VTUEEE (Vel Tech entrance exam) or JEE Main score.",
        "admission_pg": "Through GATE or Vel Tech entrance exam.",
        "admission_docs": "Entrance Exam Score; 10th & 12th Marksheets; TC; Photos",
        "admission_cutoff": "Entrance exam rank-based",
        "placement_avg": "₹4.5 LPA",
        "placement_highest": "₹15 LPA",
        "placement_median": "₹3.5 LPA",
        "placement_rate": "75%",
        "placement_recruiters": "TCS; Infosys; Wipro; CTS; HCL; Accenture; L&T; Hyundai",
        "facilities": "100-acre campus; Library; Hostels; Research Labs; Sports; Canteen; Auditorium",
        "website": "https://www.veltech.edu.in",
        "phone": "+91-44-26840714",
        "email": "admissions@veltech.edu.in",
        "highlights": "Deemed University; Aerospace and satellite research; NIRF ranked; Research focus; Multiple campuses",
        "description": "Vel Tech is a deemed university in Chennai known for its satellite launch achievement and growing research output."
    },
]
